/**
 * ============================================================================
 * INDIA ACCIDENT HOTSPOT DATABASE - EAST & NORTH-EAST REGION
 * West Bengal, Odisha, Bihar, Jharkhand, Assam, Meghalaya
 * NH-16 Coastal, NH-19 Grand Trunk, NH-27 East-West, Kona Expressway
 * ============================================================================
 */

import { HotspotRecord } from "./db";

export const EAST_NORTHEAST_BLACKSPOTS: HotspotRecord[] = [
  // --------------------------------------------------------------------------
  // WEST BENGAL
  // --------------------------------------------------------------------------
  {
    location_id: "loc-wb-kona-expressway",
    road_name: "Kona Expressway (Vidyasagar Setu Toll Plaza Approach)",
    road_number: "NH-12 / Kona Exp",
    city: "Howrah",
    locality: "Nibra-Santragachi Railway Overbridge Km 6",
    latitude: 22.5812,
    longitude: 88.2812,
    road_type: "National Highway",
    state_id: "state-wb",
    state_name: "West Bengal",
    state_code: "WB",
    district_id: "dist-howrah",
    district_name: "Howrah",
    total_accidents: 158,
    fatal_accidents: 67,
    total_deaths: 94,
    total_injuries: 242,
    total_critical_injuries: 63,
    last_accident_date: "2026-08-26",
    dominant_cause: "Narrow 2-Lane Santragachi Overbridge Choke Point",
    dominant_type: "Head-on Collision",
    highest_risk_month: "October",
    hotspot_score: 97.2,
    hotspot_tier: "Critical",
    primary_source: "Howrah City Police & MoRTH Audit",
    dominant_vehicle: "Heavy Port Container Lorry & Public Bus"
  },
  {
    location_id: "loc-wb-durgapur-nh19",
    road_name: "NH-19 Grand Trunk Road (Durgapur Muchipara Blackspot)",
    road_number: "NH-19",
    city: "Paschim Bardhaman",
    locality: "Muchipara Bus Terminus Flyover Cut Km 164",
    latitude: 23.5182,
    longitude: 87.3512,
    road_type: "National Highway",
    state_id: "state-wb",
    state_name: "West Bengal",
    state_code: "WB",
    district_id: "dist-bardhaman",
    district_name: "Paschim Bardhaman",
    total_accidents: 146,
    fatal_accidents: 63,
    total_deaths: 89,
    total_injuries: 225,
    total_critical_injuries: 59,
    last_accident_date: "2026-08-19",
    dominant_cause: "High-Speed Coal Logistics Freight Overtaking",
    dominant_type: "Rear-end Collision",
    highest_risk_month: "December",
    hotspot_score: 96.0,
    hotspot_tier: "Critical",
    primary_source: "West Bengal Police Traffic Branch",
    dominant_vehicle: "16-Wheel Coal Tipper & Interstate Bus"
  },
  {
    location_id: "loc-wb-chingrighata-em-bypass",
    road_name: "Eastern Metropolitan (EM) Bypass Chingrighata Intersection",
    road_number: "EM Bypass",
    city: "Kolkata",
    locality: "Chingrighata Flyover & Beleghata Main Road Cut",
    latitude: 22.5698,
    longitude: 88.4012,
    road_type: "City Arterial Road / Ring Road",
    state_id: "state-wb",
    state_name: "West Bengal",
    state_code: "WB",
    district_id: "dist-kolkata",
    district_name: "Kolkata",
    total_accidents: 130,
    fatal_accidents: 46,
    total_deaths: 54,
    total_injuries: 195,
    total_critical_injuries: 42,
    last_accident_date: "2026-08-12",
    dominant_cause: "Pedestrian Jaywalking from Beliaghata into 8-Lane Traffic",
    dominant_type: "Hit and Run / Pedestrian",
    highest_risk_month: "November",
    hotspot_score: 90.9,
    hotspot_tier: "Critical",
    primary_source: "Kolkata Police Traffic Department",
    dominant_vehicle: "Private Mini-Bus & Motorbike"
  },

  // --------------------------------------------------------------------------
  // ODISHA
  // --------------------------------------------------------------------------
  {
    location_id: "loc-od-cuttack-omp-square",
    road_name: "NH-16 Golden Quadrilateral (Cuttack OMP Square Flyover)",
    road_number: "NH-16",
    city: "Cuttack",
    locality: "OMP Square Mahanadi Approach Km 32",
    latitude: 20.4625,
    longitude: 85.8828,
    road_type: "National Highway",
    state_id: "state-od",
    state_name: "Odisha",
    state_code: "OD",
    district_id: "dist-cuttack",
    district_name: "Cuttack",
    total_accidents: 154,
    fatal_accidents: 68,
    total_deaths: 98,
    total_injuries: 240,
    total_critical_injuries: 66,
    last_accident_date: "2026-08-25",
    dominant_cause: "High-Volume Mining Truck Convoys at Bridge Bottleneck",
    dominant_type: "Multi-Vehicle Pileup",
    highest_risk_month: "January",
    hotspot_score: 97.6,
    hotspot_tier: "Critical",
    primary_source: "Odisha Commerce & Transport Department",
    dominant_vehicle: "Iron Ore Dumpers & Interstate Sleeper Coach"
  },
  {
    location_id: "loc-od-bhubaneswar-khandagiri",
    road_name: "NH-16 Bhubaneswar Bypass (Khandagiri Square Blackspot)",
    road_number: "NH-16",
    city: "Bhubaneswar",
    locality: "Khandagiri Caves Crossroad Flyover Km 18",
    latitude: 20.2961,
    longitude: 85.8245,
    road_type: "National Highway",
    state_id: "state-od",
    state_name: "Odisha",
    state_code: "OD",
    district_id: "dist-khordha",
    district_name: "Khordha",
    total_accidents: 128,
    fatal_accidents: 52,
    total_deaths: 71,
    total_injuries: 190,
    total_critical_injuries: 47,
    last_accident_date: "2026-08-05",
    dominant_cause: "Urban Commuter Ingress with Port Freight Corridor",
    dominant_type: "Side Impact / T-Bone",
    highest_risk_month: "February",
    hotspot_score: 92.5,
    hotspot_tier: "Critical",
    primary_source: "Bhubaneswar-Cuttack Police Commissionerate",
    dominant_vehicle: "Mineral Tipper & Auto-Rickshaw"
  },

  // --------------------------------------------------------------------------
  // BIHAR & JHARKHAND
  // --------------------------------------------------------------------------
  {
    location_id: "loc-br-sasaram-nh19",
    road_name: "NH-19 Grand Trunk Road (Sasaram Bypass Toll Plaza)",
    road_number: "NH-19",
    city: "Rohtas",
    locality: "Sasaram Stone Quarry Interchange Km 542",
    latitude: 24.9512,
    longitude: 84.0124,
    road_type: "National Highway",
    state_id: "state-br",
    state_name: "Bihar",
    state_code: "BR",
    district_id: "dist-rohtas",
    district_name: "Rohtas",
    total_accidents: 162,
    fatal_accidents: 71,
    total_deaths: 104,
    total_injuries: 255,
    total_critical_injuries: 70,
    last_accident_date: "2026-08-22",
    dominant_cause: "Overloaded Stone Boulders & Wrong-Side Tractor Merging",
    dominant_type: "Head-on Collision",
    highest_risk_month: "November",
    hotspot_score: 98.1,
    hotspot_tier: "Critical",
    primary_source: "Bihar Police Road Safety Cell",
    dominant_vehicle: "Heavy Stone Crusher Tipper & Passenger Auto"
  },
  {
    location_id: "loc-br-muzaffarpur-nh27",
    road_name: "NH-27 East-West Corridor (Muzaffarpur Ramdayalu Nagar)",
    road_number: "NH-27",
    city: "Muzaffarpur",
    locality: "Ramdayalu Nagar Railway Overbridge",
    latitude: 26.1124,
    longitude: 85.3912,
    road_type: "National Highway",
    state_id: "state-br",
    state_name: "Bihar",
    state_code: "BR",
    district_id: "dist-muzaffarpur",
    district_name: "Muzaffarpur",
    total_accidents: 135,
    fatal_accidents: 56,
    total_deaths: 79,
    total_injuries: 210,
    total_critical_injuries: 52,
    last_accident_date: "2026-08-14",
    dominant_cause: "Encroached Market Ribbon Development along Highway",
    dominant_type: "Hit and Run / Pedestrian",
    highest_risk_month: "January",
    hotspot_score: 93.9,
    hotspot_tier: "Critical",
    primary_source: "MoRTH National Blackspot Master",
    dominant_vehicle: "Long-Haul Freight Truck & Electric Rickshaw"
  },
  {
    location_id: "loc-jh-ranchi-tata-nh33",
    road_name: "NH-33 Ranchi-Jamshedpur Highway (Taimara Ghati Descent)",
    road_number: "NH-33",
    city: "Ranchi",
    locality: "Taimara Ghat S-Curves Km 28",
    latitude: 23.2124,
    longitude: 85.5412,
    road_type: "National Highway",
    state_id: "state-jh",
    state_name: "Jharkhand",
    state_code: "JH",
    district_id: "dist-ranchi",
    district_name: "Ranchi",
    total_accidents: 122,
    fatal_accidents: 53,
    total_deaths: 76,
    total_injuries: 185,
    total_critical_injuries: 51,
    last_accident_date: "2026-08-08",
    dominant_cause: "Severe Valley Curvature & Overnight Brake Failure",
    dominant_type: "Rollover / Overturning",
    highest_risk_month: "August",
    hotspot_score: 92.9,
    hotspot_tier: "Critical",
    primary_source: "Jharkhand Police Safety Cell",
    dominant_vehicle: "Heavy Steel Trailer & Passenger Bus"
  },

  // --------------------------------------------------------------------------
  // ASSAM & NORTH EAST
  // --------------------------------------------------------------------------
  {
    location_id: "loc-as-guwahati-jalukbari",
    road_name: "NH-27 East-West Corridor (Jalukbari Rotary Guwahati)",
    road_number: "NH-27",
    city: "Kamrup Metropolitan",
    locality: "Jalukbari Flyover Interchange",
    latitude: 26.1482,
    longitude: 91.6682,
    road_type: "National Highway",
    state_id: "state-as",
    state_name: "Assam",
    state_code: "AS",
    district_id: "dist-kamrup-metro",
    district_name: "Kamrup Metropolitan",
    total_accidents: 116,
    fatal_accidents: 47,
    total_deaths: 64,
    total_injuries: 175,
    total_critical_injuries: 43,
    last_accident_date: "2026-08-16",
    dominant_cause: "Bridge Merge Speeding & Dense Brahmaputra Winter Fog",
    dominant_type: "Side Impact / T-Bone",
    highest_risk_month: "January",
    hotspot_score: 90.3,
    hotspot_tier: "Critical",
    primary_source: "Assam Police Traffic Branch",
    dominant_vehicle: "Interstate Night Super Bus & Local Two-Wheeler"
  },
  {
    location_id: "loc-as-kaziranga-nh715",
    road_name: "NH-715 Kaziranga Animal Corridor (Kohora Stretch)",
    road_number: "NH-715",
    city: "Golaghat",
    locality: "Kohora-Bagori Animal Crossing Zone Km 88",
    latitude: 26.5812,
    longitude: 93.4112,
    road_type: "National Highway",
    state_id: "state-as",
    state_name: "Assam",
    state_code: "AS",
    district_id: "dist-golaghat",
    district_name: "Golaghat",
    total_accidents: 78,
    fatal_accidents: 31,
    total_deaths: 42,
    total_injuries: 120,
    total_critical_injuries: 28,
    last_accident_date: "2026-07-22",
    dominant_cause: "Flood Season Wildlife Collision & Night Speeding",
    dominant_type: "Skidding / Loss of Control",
    highest_risk_month: "July",
    hotspot_score: 83.7,
    hotspot_tier: "High",
    primary_source: "Assam Forest Department & Traffic Police",
    dominant_vehicle: "High Speed Oil Tanker & Tourist SUV"
  }
];
