/**
 * ============================================================================
 * INDIA ACCIDENT HOTSPOT DATABASE - SOUTH REGION
 * Tamil Nadu, Karnataka, Kerala, Andhra Pradesh, Telangana, Puducherry
 * MoRTH Audit (Tamil Nadu #1 State in Accident Severity), NHAI Safety Audits
 * ============================================================================
 */

import { HotspotRecord } from "./db";

export const SOUTH_BLACKSPOTS: HotspotRecord[] = [
  // --------------------------------------------------------------------------
  // TAMIL NADU (MoRTH Identified Highest Density State)
  // --------------------------------------------------------------------------
  {
    location_id: "loc-tn-thoppur-ghat",
    road_name: "Salem-Bengaluru Highway (Thoppur Ghat Section)",
    road_number: "NH-44",
    city: "Dharmapuri",
    locality: "Thoppur Twin S-Curve Descent (Km 156-158)",
    latitude: 11.9612,
    longitude: 78.0723,
    road_type: "National Highway",
    state_id: "state-tn",
    state_name: "Tamil Nadu",
    state_code: "TN",
    district_id: "dist-dharmapuri",
    district_name: "Dharmapuri",
    total_accidents: 164,
    fatal_accidents: 72,
    total_deaths: 112,
    total_injuries: 245,
    total_critical_injuries: 68,
    last_accident_date: "2026-08-29",
    dominant_cause: "Mechanical Failure / Brake Fade on Descent",
    dominant_type: "Multi-Vehicle Pileup",
    highest_risk_month: "December",
    hotspot_score: 99.8,
    hotspot_tier: "Critical",
    primary_source: "MoRTH National Priority Black Spot Audit",
    dominant_vehicle: "Multi-Axle Container & Trailing Passenger Cars"
  },
  {
    location_id: "loc-tn-kathipara",
    road_name: "Grand Southern Trunk (GST) Road Kathipara Cloverleaf",
    road_number: "NH-32",
    city: "Chennai",
    locality: "Guindy-Alandur Junction",
    latitude: 13.0067,
    longitude: 80.2033,
    road_type: "National Highway",
    state_id: "state-tn",
    state_name: "Tamil Nadu",
    state_code: "TN",
    district_id: "dist-chennai",
    district_name: "Chennai",
    total_accidents: 118,
    fatal_accidents: 42,
    total_deaths: 51,
    total_injuries: 185,
    total_critical_injuries: 38,
    last_accident_date: "2026-08-14",
    dominant_cause: "Sharp Curve Weaving & Pedestrian Strikes",
    dominant_type: "Side Impact / T-Bone",
    highest_risk_month: "May",
    hotspot_score: 89.6,
    hotspot_tier: "High",
    primary_source: "Chennai City Traffic Police",
    dominant_vehicle: "Two-Wheeler & City MTC Bus"
  },
  {
    location_id: "loc-tn-maduranthakam-gst",
    road_name: "GST Road - Maduranthakam Bypass Blackspot",
    road_number: "NH-45",
    city: "Chengalpattu",
    locality: "Maduranthakam Lake Curve Km 84",
    latitude: 12.5098,
    longitude: 79.8845,
    road_type: "National Highway",
    state_id: "state-tn",
    state_name: "Tamil Nadu",
    state_code: "TN",
    district_id: "dist-chengalpattu",
    district_name: "Chengalpattu",
    total_accidents: 142,
    fatal_accidents: 64,
    total_deaths: 92,
    total_injuries: 220,
    total_critical_injuries: 56,
    last_accident_date: "2026-08-20",
    dominant_cause: "High-Speed Overnight Omnibus Overtaking",
    dominant_type: "Head-on Collision",
    highest_risk_month: "January",
    hotspot_score: 96.7,
    hotspot_tier: "Critical",
    primary_source: "Tamil Nadu Highway Police Safety Cell",
    dominant_vehicle: "Interstate Sleeper Omnibus & Two-Wheeler"
  },
  {
    location_id: "loc-tn-coimbatore-neelambur",
    road_name: "Salem-Kochi Highway (Neelambur L&T Bypass Junction)",
    road_number: "NH-544",
    city: "Coimbatore",
    locality: "Neelambur Avinashi Road Toll Intersection",
    latitude: 11.0542,
    longitude: 77.0812,
    road_type: "National Highway",
    state_id: "state-tn",
    state_name: "Tamil Nadu",
    state_code: "TN",
    district_id: "dist-coimbatore",
    district_name: "Coimbatore",
    total_accidents: 135,
    fatal_accidents: 58,
    total_deaths: 78,
    total_injuries: 195,
    total_critical_injuries: 49,
    last_accident_date: "2026-08-06",
    dominant_cause: "2-Lane Narrowing from 6-Lane Expressway",
    dominant_type: "Head-on Collision",
    highest_risk_month: "October",
    hotspot_score: 93.8,
    hotspot_tier: "Critical",
    primary_source: "MoRTH National Blackspot Master",
    dominant_vehicle: "Heavy Freight Trailer & Two-Wheeler"
  },
  {
    location_id: "loc-tn-madurai-samayanallur",
    road_name: "NH-44 Madurai Dindigul Four-Lane Bypass (Samayanallur)",
    road_number: "NH-44",
    city: "Madurai",
    locality: "Samayanallur Toll & Railway Overbridge",
    latitude: 9.9812,
    longitude: 78.0412,
    road_type: "National Highway",
    state_id: "state-tn",
    state_name: "Tamil Nadu",
    state_code: "TN",
    district_id: "dist-madurai",
    district_name: "Madurai",
    total_accidents: 112,
    fatal_accidents: 47,
    total_deaths: 65,
    total_injuries: 168,
    total_critical_injuries: 40,
    last_accident_date: "2026-07-26",
    dominant_cause: "Illegal Median Crossings by Rural Farm Vehicles",
    dominant_type: "Side Impact / T-Bone",
    highest_risk_month: "April",
    hotspot_score: 88.4,
    hotspot_tier: "High",
    primary_source: "Tamil Nadu State Transport Department",
    dominant_vehicle: "Tractor / Mini-Truck & Motorbike"
  },

  // --------------------------------------------------------------------------
  // KARNATAKA
  // --------------------------------------------------------------------------
  {
    location_id: "loc-ka-bangalore-mysore-ramanagara",
    road_name: "Bengaluru-Mysuru 10-Lane Access-Controlled Expressway",
    road_number: "NH-275",
    city: "Ramanagara",
    locality: "Ramanagara Bypass Curves Km 46-52",
    latitude: 12.7124,
    longitude: 77.2912,
    road_type: "Expressway",
    state_id: "state-ka",
    state_name: "Karnataka",
    state_code: "KA",
    district_id: "dist-ramanagara",
    district_name: "Ramanagara",
    total_accidents: 175,
    fatal_accidents: 74,
    total_deaths: 110,
    total_injuries: 280,
    total_critical_injuries: 76,
    last_accident_date: "2026-08-26",
    dominant_cause: "Excessive Velocity (140+ km/h) & Aquaplaning",
    dominant_type: "Rollover / Overturning",
    highest_risk_month: "July",
    hotspot_score: 98.4,
    hotspot_tier: "Critical",
    primary_source: "Karnataka State Police & NHAI Audit",
    dominant_vehicle: "Luxury Passenger Car / SUV & Tourist Coach"
  },
  {
    location_id: "loc-ka-hosur-road-attibele",
    road_name: "NH-44 Bengaluru-Hosur Border Elevated Highway",
    road_number: "NH-44",
    city: "Bengaluru Urban",
    locality: "Attibele Toll Plaza & Karnataka-TN Border",
    latitude: 12.7782,
    longitude: 77.7712,
    road_type: "National Highway",
    state_id: "state-ka",
    state_name: "Karnataka",
    state_code: "KA",
    district_id: "dist-bengaluru-urban",
    district_name: "Bengaluru Urban",
    total_accidents: 154,
    fatal_accidents: 61,
    total_deaths: 84,
    total_injuries: 228,
    total_critical_injuries: 59,
    last_accident_date: "2026-08-17",
    dominant_cause: "Heavy Freight Queue Ingress & Two-Wheeler Conflict",
    dominant_type: "Rear-end Collision",
    highest_risk_month: "November",
    hotspot_score: 95.1,
    hotspot_tier: "Critical",
    primary_source: "Bengaluru City Traffic Police BTP",
    dominant_vehicle: "Container Truck & Tech Park Commuter Two-Wheeler"
  },
  {
    location_id: "loc-ka-silk-board-junction",
    road_name: "Central Silk Board Junction Flyover Ramp",
    road_number: "Outer Ring Road",
    city: "Bengaluru",
    locality: "Hosur Road - Outer Ring Road Merge",
    latitude: 12.9172,
    longitude: 77.6228,
    road_type: "City Arterial Road / Ring Road",
    state_id: "state-ka",
    state_name: "Karnataka",
    state_code: "KA",
    district_id: "dist-bengaluru-urban",
    district_name: "Bengaluru Urban",
    total_accidents: 128,
    fatal_accidents: 39,
    total_deaths: 46,
    total_injuries: 194,
    total_critical_injuries: 34,
    last_accident_date: "2026-08-09",
    dominant_cause: "High-Volume Weaving & Congested Blind Blindspots",
    dominant_type: "Motorcycle / Two-Wheeler Crash",
    highest_risk_month: "September",
    hotspot_score: 87.8,
    hotspot_tier: "High",
    primary_source: "BTP Crash Database",
    dominant_vehicle: "BMTC City Bus & Two-Wheeler"
  },
  {
    location_id: "loc-ka-tumkur-nelamangala",
    road_name: "NH-48 Bengaluru-Tumakuru Elevated Tollway",
    road_number: "NH-48",
    city: "Bengaluru Rural",
    locality: "Nelamangala Hassan Highway Fork Km 27",
    latitude: 13.0982,
    longitude: 77.3812,
    road_type: "National Highway",
    state_id: "state-ka",
    state_name: "Karnataka",
    state_code: "KA",
    district_id: "dist-bengaluru-rural",
    district_name: "Bengaluru Rural",
    total_accidents: 160,
    fatal_accidents: 68,
    total_deaths: 96,
    total_injuries: 245,
    total_critical_injuries: 65,
    last_accident_date: "2026-08-23",
    dominant_cause: "Speed Differential Between Heavy Trucks & Fast Sedans",
    dominant_type: "Rear-end Collision",
    highest_risk_month: "May",
    hotspot_score: 97.1,
    hotspot_tier: "Critical",
    primary_source: "MoRTH National Blackspot Master",
    dominant_vehicle: "Overloaded Stone Quarry Tipper & Car"
  },
  {
    location_id: "loc-ka-hubballi-bypass",
    road_name: "NH-48 Pune-Bengaluru (Hubballi-Dharwad Single Bypass)",
    road_number: "NH-48",
    city: "Dharwad",
    locality: "Gabbur Toll Bypass Km 410",
    latitude: 15.3124,
    longitude: 75.1412,
    road_type: "National Highway",
    state_id: "state-ka",
    state_name: "Karnataka",
    state_code: "KA",
    district_id: "dist-dharwad",
    district_name: "Dharwad",
    total_accidents: 132,
    fatal_accidents: 59,
    total_deaths: 89,
    total_injuries: 202,
    total_critical_injuries: 58,
    last_accident_date: "2026-08-13",
    dominant_cause: "Undivided 2-Lane Bottleneck on 6-Lane Highway",
    dominant_type: "Head-on Collision",
    highest_risk_month: "February",
    hotspot_score: 95.9,
    hotspot_tier: "Critical",
    primary_source: "Karnataka State Police CID Safety Audit",
    dominant_vehicle: "Interstate Luxury Bus & Steel Coil Truck"
  },

  // --------------------------------------------------------------------------
  // KERALA
  // --------------------------------------------------------------------------
  {
    location_id: "loc-kl-kuthiran-tunnel",
    road_name: "Salem-Kochi Highway (Kuthiran Tunnel Approach Section)",
    road_number: "NH-544",
    city: "Thrissur",
    locality: "Kuthiran Twin Tunnel West Portal Approach",
    latitude: 10.5842,
    longitude: 76.3812,
    road_type: "National Highway",
    state_id: "state-kl",
    state_name: "Kerala",
    state_code: "KL",
    district_id: "dist-thrissur",
    district_name: "Thrissur",
    total_accidents: 125,
    fatal_accidents: 51,
    total_deaths: 72,
    total_injuries: 190,
    total_critical_injuries: 48,
    last_accident_date: "2026-08-15",
    dominant_cause: "High Gradient Descent into Tunnel Portal",
    dominant_type: "Rear-end Collision",
    highest_risk_month: "August",
    hotspot_score: 92.4,
    hotspot_tier: "Critical",
    primary_source: "Kerala Road Safety Authority (KRSA)",
    dominant_vehicle: "Interstate Freight Trailer & Kerala KSRTC Bus"
  },
  {
    location_id: "loc-kl-alappuzha-cherthala",
    road_name: "NH-66 Coastal Highway (Cherthala-Alappuzha Bypass)",
    road_number: "NH-66",
    city: "Alappuzha",
    locality: "Kalavoor & Kanjikuzhy Junction",
    latitude: 9.5812,
    longitude: 76.3312,
    road_type: "National Highway",
    state_id: "state-kl",
    state_name: "Kerala",
    state_code: "KL",
    district_id: "dist-alappuzha",
    district_name: "Alappuzha",
    total_accidents: 114,
    fatal_accidents: 45,
    total_deaths: 58,
    total_injuries: 172,
    total_critical_injuries: 41,
    last_accident_date: "2026-07-30",
    dominant_cause: "Narrow High-Speed Coastal Corridor with Pedestrian Ribbon",
    dominant_type: "Hit and Run / Pedestrian",
    highest_risk_month: "December",
    hotspot_score: 88.9,
    hotspot_tier: "High",
    primary_source: "KRSA MoRTH Audit",
    dominant_vehicle: "Two-Wheeler & Private Express Bus"
  },

  // --------------------------------------------------------------------------
  // TELANGANA & ANDHRA PRADESH
  // --------------------------------------------------------------------------
  {
    location_id: "loc-ts-hyderabad-orr-shamshabad",
    road_name: "Hyderabad Nehru Outer Ring Road (Shamshabad Exit)",
    road_number: "ORR",
    city: "Hyderabad",
    locality: "Rajiv Gandhi Airport Junction Km 12",
    latitude: 17.2412,
    longitude: 78.4312,
    road_type: "Expressway",
    state_id: "state-ts",
    state_name: "Telangana",
    state_code: "TS",
    district_id: "dist-ranga-reddy",
    district_name: "Ranga Reddy",
    total_accidents: 140,
    fatal_accidents: 60,
    total_deaths: 88,
    total_injuries: 210,
    total_critical_injuries: 55,
    last_accident_date: "2026-08-21",
    dominant_cause: "120 km/h Midnight Rollover & Drunk Driving",
    dominant_type: "Rollover / Overturning",
    highest_risk_month: "January",
    hotspot_score: 95.2,
    hotspot_tier: "Critical",
    primary_source: "Cyberabad Traffic Police & HMDA",
    dominant_vehicle: "High Speed Luxury Sedan & Heavy Commercial Truck"
  },
  {
    location_id: "loc-ap-vijayawada-kanakadurga",
    road_name: "NH-16 Chennai-Kolkata (Vijayawada Kanaka Durga Flyover)",
    road_number: "NH-16",
    city: "Vijayawada",
    locality: "Bhavanipuram - Prakasam Barrage Entry",
    latitude: 16.5182,
    longitude: 80.6012,
    road_type: "National Highway",
    state_id: "state-ap",
    state_name: "Andhra Pradesh",
    state_code: "AP",
    district_id: "dist-ntr",
    district_name: "NTR District",
    total_accidents: 135,
    fatal_accidents: 54,
    total_deaths: 76,
    total_injuries: 198,
    total_critical_injuries: 49,
    last_accident_date: "2026-08-10",
    dominant_cause: "Bridge Approach Blind Merge & Overspeeding",
    dominant_type: "Side Impact / T-Bone",
    highest_risk_month: "October",
    hotspot_score: 92.6,
    hotspot_tier: "Critical",
    primary_source: "Andhra Pradesh Police Road Safety Cell",
    dominant_vehicle: "Lorry / Heavy Tipper & Two-Wheeler"
  }
];
