/**
 * ============================================================================
 * INDIA ACCIDENT HOTSPOT DATABASE - NORTH REGION
 * Delhi, Uttar Pradesh, Haryana, Punjab, Rajasthan, Himachal, Uttarakhand, J&K
 * Verified MoRTH Blackspots, NCRB Audits, NHAI Road Safety Inspection Reports
 * ============================================================================
 */

import { HotspotRecord } from "./db";

export const NORTH_BLACKSPOTS: HotspotRecord[] = [
  // --------------------------------------------------------------------------
  // DELHI NCR
  // --------------------------------------------------------------------------
  {
    location_id: "loc-dl-mukarba-chowk",
    road_name: "Outer Ring Road - GT Karnal Road Interchange (Mukarba Chowk)",
    road_number: "NH-44",
    city: "New Delhi",
    locality: "Mukarba Chowk Flyover & Underpass Complex",
    latitude: 28.7364,
    longitude: 77.1589,
    road_type: "National Highway",
    state_id: "state-dl",
    state_name: "Delhi",
    state_code: "DL",
    district_id: "dist-delhi-north",
    district_name: "North Delhi",
    total_accidents: 198,
    fatal_accidents: 82,
    total_deaths: 96,
    total_injuries: 260,
    total_critical_injuries: 74,
    last_accident_date: "2026-08-28",
    dominant_cause: "High Speed Merge & Pedestrian Crossing",
    dominant_type: "Hit and Run / Multi-Vehicle Pileup",
    highest_risk_month: "January",
    hotspot_score: 99.2,
    hotspot_tier: "Critical",
    primary_source: "Delhi Traffic Police & MoRTH Audit",
    dominant_vehicle: "Truck / Inter-State Container / Bus"
  },
  {
    location_id: "loc-dl-kashmere-gate",
    road_name: "Mahatma Gandhi Ring Road (ISBT Kashmere Gate)",
    road_number: "Ring Road",
    city: "New Delhi",
    locality: "Yudhisthir Setu & Nigambodh Ghat Cut",
    latitude: 28.6678,
    longitude: 77.2341,
    road_type: "City Arterial Road / Ring Road",
    state_id: "state-dl",
    state_name: "Delhi",
    state_code: "DL",
    district_id: "dist-delhi-central",
    district_name: "Central Delhi",
    total_accidents: 142,
    fatal_accidents: 58,
    total_deaths: 68,
    total_injuries: 195,
    total_critical_injuries: 48,
    last_accident_date: "2026-08-11",
    dominant_cause: "Unregulated Bus Reversals & Pedestrian Conflict",
    dominant_type: "Hit and Run / Pedestrian",
    highest_risk_month: "December",
    hotspot_score: 93.4,
    hotspot_tier: "Critical",
    primary_source: "Delhi Traffic Police MoRTH Audit",
    dominant_vehicle: "Interstate Bus & Two-Wheeler"
  },
  {
    location_id: "loc-dl-sarai-kale-khan",
    road_name: "Ring Road - Delhi-Meerut Expressway Junction (Sarai Kale Khan)",
    road_number: "NH-9",
    city: "New Delhi",
    locality: "ISBT & Nizamuddin Railway Approach Flyover",
    latitude: 28.5891,
    longitude: 77.2589,
    road_type: "National Highway",
    state_id: "state-dl",
    state_name: "Delhi",
    state_code: "DL",
    district_id: "dist-delhi-southeast",
    district_name: "South East Delhi",
    total_accidents: 165,
    fatal_accidents: 64,
    total_deaths: 79,
    total_injuries: 215,
    total_critical_injuries: 52,
    last_accident_date: "2026-08-19",
    dominant_cause: "Sudden Weaving at Multi-tier Flyovers",
    dominant_type: "Side Impact / T-Bone",
    highest_risk_month: "November",
    hotspot_score: 95.8,
    hotspot_tier: "Critical",
    primary_source: "MoRTH National Blackspot Master",
    dominant_vehicle: "Commercial LCV & Passenger Cabs"
  },
  {
    location_id: "loc-dl-mahipalpur",
    road_name: "NH-48 Mahipalpur Flyover & Airport Aerocity Underpass",
    road_number: "NH-48",
    city: "New Delhi",
    locality: "Radisson Blu Curve & Terminal 3 Merge",
    latitude: 28.5489,
    longitude: 77.1214,
    road_type: "National Highway",
    state_id: "state-dl",
    state_name: "Delhi",
    state_code: "DL",
    district_id: "dist-delhi-southwest",
    district_name: "South West Delhi",
    total_accidents: 130,
    fatal_accidents: 52,
    total_deaths: 61,
    total_injuries: 180,
    total_critical_injuries: 39,
    last_accident_date: "2026-07-31",
    dominant_cause: "High-Speed Midnight Merging to Airport",
    dominant_type: "Rear-end Collision",
    highest_risk_month: "February",
    hotspot_score: 91.2,
    hotspot_tier: "Critical",
    primary_source: "Delhi Traffic Police",
    dominant_vehicle: "App Cabs & Heavy Airport Cargo Trucks"
  },
  {
    location_id: "loc-dl-peeragarhi",
    road_name: "Rohtak Road Outer Ring Road Junction (Peeragarhi Chowk)",
    road_number: "NH-10",
    city: "New Delhi",
    locality: "Peeragarhi Metro Intersection",
    latitude: 28.6789,
    longitude: 77.0912,
    road_type: "National Highway",
    state_id: "state-dl",
    state_name: "Delhi",
    state_code: "DL",
    district_id: "dist-delhi-west",
    district_name: "West Delhi",
    total_accidents: 115,
    fatal_accidents: 45,
    total_deaths: 53,
    total_injuries: 160,
    total_critical_injuries: 34,
    last_accident_date: "2026-07-24",
    dominant_cause: "Signal Jumping & Encroached Kerb Pedestrian Strikes",
    dominant_type: "Side Impact / T-Bone",
    highest_risk_month: "May",
    hotspot_score: 87.5,
    hotspot_tier: "High",
    primary_source: "Delhi Traffic Police MoRTH Audit",
    dominant_vehicle: "Two-Wheeler & Heavy Dumper"
  },

  // --------------------------------------------------------------------------
  // UTTAR PRADESH
  // --------------------------------------------------------------------------
  {
    location_id: "loc-up-yamuna-exp-km88",
    road_name: "Yamuna Expressway (Bajna-Surir Stretch Km 88-92)",
    road_number: "Yamuna Expressway",
    city: "Mathura",
    locality: "Milepost 88 Agricultural Cut",
    latitude: 27.8124,
    longitude: 77.7912,
    road_type: "Expressway",
    state_id: "state-up",
    state_name: "Uttar Pradesh",
    state_code: "UP",
    district_id: "dist-mathura",
    district_name: "Mathura",
    total_accidents: 178,
    fatal_accidents: 76,
    total_deaths: 115,
    total_injuries: 290,
    total_critical_injuries: 82,
    last_accident_date: "2026-08-25",
    dominant_cause: "Tyre Burst due to High Friction on Rigid Concrete",
    dominant_type: "Rollover / Overturning",
    highest_risk_month: "January",
    hotspot_score: 98.9,
    hotspot_tier: "Critical",
    primary_source: "YEIDA Safety Audit & MoRTH Report",
    dominant_vehicle: "SUV / Tourist Bus / Passenger Sedan"
  },
  {
    location_id: "loc-up-yamuna-exp-jewar",
    road_name: "Yamuna Expressway Jewar Airport Interchange (Km 38)",
    road_number: "Yamuna Expressway",
    city: "Gautam Buddha Nagar",
    locality: "Jewar Smart Interchange Km 38",
    latitude: 28.1812,
    longitude: 77.6412,
    road_type: "Expressway",
    state_id: "state-up",
    state_name: "Uttar Pradesh",
    state_code: "UP",
    district_id: "dist-gb-nagar",
    district_name: "Gautam Buddha Nagar",
    total_accidents: 124,
    fatal_accidents: 49,
    total_deaths: 72,
    total_injuries: 185,
    total_critical_injuries: 46,
    last_accident_date: "2026-08-08",
    dominant_cause: "Zero Visibility Winter Fog Blind Pileup",
    dominant_type: "Multi-Vehicle Pileup",
    highest_risk_month: "December",
    hotspot_score: 94.6,
    hotspot_tier: "Critical",
    primary_source: "MoRTH - Road Accidents in India",
    dominant_vehicle: "Multi-Axle Trailer & Private Car"
  },
  {
    location_id: "loc-up-agra-lucknow-kannauj",
    road_name: "Agra-Lucknow Expressway (Kannauj Airstrip Stretch Km 152)",
    road_number: "Agra-Lucknow Exp",
    city: "Kannauj",
    locality: "Emergency IAF Runway Km 152-155",
    latitude: 27.0542,
    longitude: 79.8431,
    road_type: "Expressway",
    state_id: "state-up",
    state_name: "Uttar Pradesh",
    state_code: "UP",
    district_id: "dist-kannauj",
    district_name: "Kannauj",
    total_accidents: 145,
    fatal_accidents: 62,
    total_deaths: 98,
    total_injuries: 240,
    total_critical_injuries: 68,
    last_accident_date: "2026-08-16",
    dominant_cause: "Driver Micro-Sleep / Falling Asleep at Night",
    dominant_type: "Rear-end Collision",
    highest_risk_month: "February",
    hotspot_score: 96.5,
    hotspot_tier: "Critical",
    primary_source: "UPEIDA Highway Safety Audit",
    dominant_vehicle: "Sleeper Bus & Container Truck"
  },
  {
    location_id: "loc-up-nh19-kanpur-ramadevi",
    road_name: "NH-19 Grand Trunk Road (Ramadevi Roundabout Kanpur)",
    road_number: "NH-19",
    city: "Kanpur",
    locality: "Ramadevi Flyover Underpass Junction",
    latitude: 26.4312,
    longitude: 80.3912,
    road_type: "National Highway",
    state_id: "state-up",
    state_name: "Uttar Pradesh",
    state_code: "UP",
    district_id: "dist-kanpur-nagar",
    district_name: "Kanpur Nagar",
    total_accidents: 210,
    fatal_accidents: 89,
    total_deaths: 124,
    total_injuries: 340,
    total_critical_injuries: 95,
    last_accident_date: "2026-08-30",
    dominant_cause: "Pedestrian Collision with Heavy Highway Freight",
    dominant_type: "Hit and Run / Pedestrian",
    highest_risk_month: "November",
    hotspot_score: 99.4,
    hotspot_tier: "Critical",
    primary_source: "MoRTH 5,803 Black Spot Audit",
    dominant_vehicle: "Truck / Multi-Axle Freight & Auto Rickshaw"
  },
  {
    location_id: "loc-up-varanasi-ring-road",
    road_name: "Varanasi Outer Ring Road - Harhua Crossroad",
    road_number: "NH-31",
    city: "Varanasi",
    locality: "Harhua Airport Highway Flyover",
    latitude: 25.3812,
    longitude: 82.9124,
    road_type: "National Highway",
    state_id: "state-up",
    state_name: "Uttar Pradesh",
    state_code: "UP",
    district_id: "dist-varanasi",
    district_name: "Varanasi",
    total_accidents: 118,
    fatal_accidents: 46,
    total_deaths: 64,
    total_injuries: 172,
    total_critical_injuries: 41,
    last_accident_date: "2026-07-28",
    dominant_cause: "Overspeeding at Uncontrolled Median Cuts",
    dominant_type: "Side Impact / T-Bone",
    highest_risk_month: "October",
    hotspot_score: 88.6,
    hotspot_tier: "High",
    primary_source: "NHAI Project Implementation Unit Varanasi",
    dominant_vehicle: "Commercial Dumper & Two-Wheeler"
  },
  {
    location_id: "loc-up-ghaziabad-dasna",
    road_name: "Delhi-Meerut Expressway - Eastern Peripheral Interchange (Dasna)",
    road_number: "NH-9",
    city: "Ghaziabad",
    locality: "Dasna Toll Plaza & Flyover Loop",
    latitude: 28.6812,
    longitude: 77.5312,
    road_type: "Expressway",
    state_id: "state-up",
    state_name: "Uttar Pradesh",
    state_code: "UP",
    district_id: "dist-ghaziabad",
    district_name: "Ghaziabad",
    total_accidents: 138,
    fatal_accidents: 54,
    total_deaths: 71,
    total_injuries: 198,
    total_critical_injuries: 51,
    last_accident_date: "2026-08-04",
    dominant_cause: "High Speed Weaving & Lane Discipline Infraction",
    dominant_type: "Rear-end Collision",
    highest_risk_month: "January",
    hotspot_score: 93.1,
    hotspot_tier: "Critical",
    primary_source: "NHAI ITS Highway Enforcement",
    dominant_vehicle: "Overloaded Mini-Truck & Private Car"
  },

  // --------------------------------------------------------------------------
  // HARYANA
  // --------------------------------------------------------------------------
  {
    location_id: "loc-hr-bilaspur-nh48",
    road_name: "Delhi-Jaipur Highway (Bilaspur Chowk Flyover)",
    road_number: "NH-48",
    city: "Gurugram",
    locality: "Bilaspur Industrial Bottleneck Km 48",
    latitude: 28.3112,
    longitude: 76.8912,
    road_type: "National Highway",
    state_id: "state-hr",
    state_name: "Haryana",
    state_code: "HR",
    district_id: "dist-gurugram",
    district_name: "Gurugram",
    total_accidents: 184,
    fatal_accidents: 78,
    total_deaths: 104,
    total_injuries: 275,
    total_critical_injuries: 79,
    last_accident_date: "2026-08-27",
    dominant_cause: "Stationary Breakdown Trucks Parked on Carriageway",
    dominant_type: "Rear-end Collision",
    highest_risk_month: "December",
    hotspot_score: 98.7,
    hotspot_tier: "Critical",
    primary_source: "Haryana Police & MoRTH Audit",
    dominant_vehicle: "Heavy Freight Trailer & Commuter Bus"
  },
  {
    location_id: "loc-hr-panipat-toll-nh44",
    road_name: "Delhi-Ambala Highway (Panipat Elevated Corridor Entry)",
    road_number: "NH-44",
    city: "Panipat",
    locality: "Panipat Toll Plaza Km 86",
    latitude: 29.3812,
    longitude: 76.9712,
    road_type: "National Highway",
    state_id: "state-hr",
    state_name: "Haryana",
    state_code: "HR",
    district_id: "dist-panipat",
    district_name: "Panipat",
    total_accidents: 156,
    fatal_accidents: 65,
    total_deaths: 88,
    total_injuries: 230,
    total_critical_injuries: 62,
    last_accident_date: "2026-08-15",
    dominant_cause: "High Velocity Toll Approach Crashes & Winter Fog",
    dominant_type: "Multi-Vehicle Pileup",
    highest_risk_month: "January",
    hotspot_score: 96.2,
    hotspot_tier: "Critical",
    primary_source: "MoRTH National Blackspot Master",
    dominant_vehicle: "Truck & Tourist Coach"
  },
  {
    location_id: "loc-hr-kmp-kundli",
    road_name: "Western Peripheral Expressway (KMP) Kundli Junction",
    road_number: "WPE / KMP",
    city: "Sonipat",
    locality: "Kundli Interchange Km 0",
    latitude: 28.8712,
    longitude: 77.1214,
    road_type: "Expressway",
    state_id: "state-hr",
    state_name: "Haryana",
    state_code: "HR",
    district_id: "dist-sonipat",
    district_name: "Sonipat",
    total_accidents: 122,
    fatal_accidents: 51,
    total_deaths: 74,
    total_injuries: 182,
    total_critical_injuries: 49,
    last_accident_date: "2026-08-01",
    dominant_cause: "Driver Fatigue & Unlit Heavy Tractor Merge",
    dominant_type: "Rear-end Collision",
    highest_risk_month: "November",
    hotspot_score: 92.8,
    hotspot_tier: "Critical",
    primary_source: "HSIIDC Expressway Safety Cell",
    dominant_vehicle: "Over-dimensional Cargo Trailer"
  },

  // --------------------------------------------------------------------------
  // RAJASTHAN
  // --------------------------------------------------------------------------
  {
    location_id: "loc-rj-jaipur-kishangarh",
    road_name: "Jaipur-Kishangarh 6-Lane Expressway (GVK Toll Road)",
    road_number: "NH-48",
    city: "Ajmer",
    locality: "Dudu-Kishangarh Border Km 328",
    latitude: 26.6812,
    longitude: 75.1214,
    road_type: "National Highway",
    state_id: "state-rj",
    state_name: "Rajasthan",
    state_code: "RJ",
    district_id: "dist-ajmer",
    district_name: "Ajmer",
    total_accidents: 172,
    fatal_accidents: 74,
    total_deaths: 108,
    total_injuries: 260,
    total_critical_injuries: 71,
    last_accident_date: "2026-08-22",
    dominant_cause: "High Speed Blowout & Stray Cattle Collision",
    dominant_type: "Rollover / Overturning",
    highest_risk_month: "June",
    hotspot_score: 97.9,
    hotspot_tier: "Critical",
    primary_source: "Rajasthan Police Traffic Cell",
    dominant_vehicle: "Marble Freight Truck & Passenger Bus"
  },
  {
    location_id: "loc-rj-udaipur-chirwa",
    road_name: "Udaipur-Nathdwara Highway (Chirwa Ghat Tunnel Section)",
    road_number: "NH-58",
    city: "Udaipur",
    locality: "Chirwa Tunnel Cut & Valley Curves",
    latitude: 24.6512,
    longitude: 73.7412,
    road_type: "National Highway",
    state_id: "state-rj",
    state_name: "Rajasthan",
    state_code: "RJ",
    district_id: "dist-udaipur",
    district_name: "Udaipur",
    total_accidents: 104,
    fatal_accidents: 42,
    total_deaths: 58,
    total_injuries: 154,
    total_critical_injuries: 37,
    last_accident_date: "2026-07-18",
    dominant_cause: "Ghat Slope Overspeeding & Brake Loss",
    dominant_type: "Head-on Collision",
    highest_risk_month: "August",
    hotspot_score: 87.2,
    hotspot_tier: "High",
    primary_source: "MoRTH Blackspot Master",
    dominant_vehicle: "Tourist Bus & Mineral Truck"
  },

  // --------------------------------------------------------------------------
  // PUNJAB & CHANDIGARH
  // --------------------------------------------------------------------------
  {
    location_id: "loc-pb-jalandhar-phagwara",
    road_name: "Grand Trunk Road (Jalandhar-Phagwara Bypass)",
    road_number: "NH-44",
    city: "Jalandhar",
    locality: "Rama Mandi Chowk Flyover Junction",
    latitude: 31.3112,
    longitude: 75.6124,
    road_type: "National Highway",
    state_id: "state-pb",
    state_name: "Punjab",
    state_code: "PB",
    district_id: "dist-jalandhar",
    district_name: "Jalandhar",
    total_accidents: 148,
    fatal_accidents: 61,
    total_deaths: 83,
    total_injuries: 218,
    total_critical_injuries: 57,
    last_accident_date: "2026-08-12",
    dominant_cause: "Winter Fog Low Visibility & Speed Violation",
    dominant_type: "Multi-Vehicle Pileup",
    highest_risk_month: "January",
    hotspot_score: 94.8,
    hotspot_tier: "Critical",
    primary_source: "Punjab Police Traffic Wing",
    dominant_vehicle: "Interstate Bus & Two-Wheeler"
  },
  {
    location_id: "loc-ch-tribune-chowk",
    road_name: "Dakshin Marg - Purv Marg Roundabout (Tribune Chowk)",
    road_number: "City Arterial",
    city: "Chandigarh",
    locality: "Tribune Chowk Rotary Km 0",
    latitude: 30.7062,
    longitude: 76.7882,
    road_type: "City Arterial Road / Ring Road",
    state_id: "state-ch",
    state_name: "Chandigarh",
    state_code: "CH",
    district_id: "dist-chandigarh",
    district_name: "Chandigarh",
    total_accidents: 88,
    fatal_accidents: 31,
    total_deaths: 39,
    total_injuries: 125,
    total_critical_injuries: 26,
    last_accident_date: "2026-07-20",
    dominant_cause: "Midnight Overspeeding & Circular Lane Intrusion",
    dominant_type: "Side Impact / T-Bone",
    highest_risk_month: "October",
    hotspot_score: 82.4,
    hotspot_tier: "High",
    primary_source: "Chandigarh Traffic Police",
    dominant_vehicle: "High Speed SUV & Motorcycle"
  },

  // --------------------------------------------------------------------------
  // UTTARAKHAND, HIMACHAL, JAMMU & KASHMIR
  // --------------------------------------------------------------------------
  {
    location_id: "loc-uk-rishikesh-devprayag",
    road_name: "Badrinath National Highway (Byasi-Devprayag Stretch)",
    road_number: "NH-58",
    city: "Tehri Garhwal",
    locality: "Byasi Landslide Curve Km 35",
    latitude: 30.1512,
    longitude: 78.4812,
    road_type: "National Highway",
    state_id: "state-uk",
    state_name: "Uttarakhand",
    state_code: "UK",
    district_id: "dist-tehri",
    district_name: "Tehri Garhwal",
    total_accidents: 96,
    fatal_accidents: 44,
    total_deaths: 68,
    total_injuries: 135,
    total_critical_injuries: 41,
    last_accident_date: "2026-08-05",
    dominant_cause: "Monsoon Landslide, Falling Rocks & Ravine Drop",
    dominant_type: "Rollover / Overturning",
    highest_risk_month: "July",
    hotspot_score: 91.5,
    hotspot_tier: "Critical",
    primary_source: "Uttarakhand Police Disaster Management",
    dominant_vehicle: "Pilgrim Maxi-Cab & Tourist Bus"
  },
  {
    location_id: "loc-hp-parwanoo-kalka",
    road_name: "Himalayan Expressway (Kalka-Parwanoo-Timber Trail)",
    road_number: "NH-5",
    city: "Solan",
    locality: "Parwanoo Bypass Sliding Zone",
    latitude: 30.8412,
    longitude: 76.9612,
    road_type: "National Highway",
    state_id: "state-hp",
    state_name: "Himachal Pradesh",
    state_code: "HP",
    district_id: "dist-solan",
    district_name: "Solan",
    total_accidents: 82,
    fatal_accidents: 35,
    total_deaths: 48,
    total_injuries: 118,
    total_critical_injuries: 30,
    last_accident_date: "2026-07-29",
    dominant_cause: "Speeding on Hill Descent & Brake Overheating",
    dominant_type: "Head-on Collision",
    highest_risk_month: "August",
    hotspot_score: 84.9,
    hotspot_tier: "High",
    primary_source: "Himachal Police Road Safety Cell",
    dominant_vehicle: "Tourist Sedan & Apple Freight Truck"
  },
  {
    location_id: "loc-jk-ramban-nh44",
    road_name: "Jammu-Srinagar National Highway (Ramban-Panthyal Slide Zone)",
    road_number: "NH-44",
    city: "Ramban",
    locality: "Khooni Nallah & Panthyal Bridge",
    latitude: 33.2412,
    longitude: 75.1912,
    road_type: "National Highway",
    state_id: "state-jk",
    state_name: "Jammu & Kashmir",
    state_code: "JK",
    district_id: "dist-ramban",
    district_name: "Ramban",
    total_accidents: 110,
    fatal_accidents: 56,
    total_deaths: 86,
    total_injuries: 165,
    total_critical_injuries: 54,
    last_accident_date: "2026-08-18",
    dominant_cause: "Shooting Stones & Sudden Road Subsidence",
    dominant_type: "Rollover / Overturning",
    highest_risk_month: "February",
    hotspot_score: 95.4,
    hotspot_tier: "Critical",
    primary_source: "J&K Traffic Police Highway Control",
    dominant_vehicle: "Military Convoy, Oil Tanker & Passenger Sumo"
  }
];
