/**
 * ============================================================================
 * INDIA ACCIDENT HOTSPOT DATABASE - WEST & CENTRAL REGION
 * Maharashtra, Gujarat, Goa, Madhya Pradesh, Chhattisgarh
 * Mumbai-Pune Expressway, Samruddhi Mahamarg, NE-1, Kasara Ghat, NH-48
 * ============================================================================
 */

import { HotspotRecord } from "./db";

export const WEST_CENTRAL_BLACKSPOTS: HotspotRecord[] = [
  // --------------------------------------------------------------------------
  // MAHARASHTRA
  // --------------------------------------------------------------------------
  {
    location_id: "loc-mh-mumbai-pune-bhor",
    road_name: "Mumbai-Pune Expressway (Bhor Ghat Section / Khandala)",
    road_number: "EXP-MH-01",
    city: "Raigad",
    locality: "Amrutanjan Point - Magic Points Km 42-45",
    latitude: 18.7812,
    longitude: 73.3512,
    road_type: "Expressway",
    state_id: "state-mh",
    state_name: "Maharashtra",
    state_code: "MH",
    district_id: "dist-raigad",
    district_name: "Raigad",
    total_accidents: 168,
    fatal_accidents: 74,
    total_deaths: 114,
    total_injuries: 265,
    total_critical_injuries: 72,
    last_accident_date: "2026-08-28",
    dominant_cause: "Brake Fade on Steep Incline & Heavy Rain Aquaplaning",
    dominant_type: "Multi-Vehicle Pileup",
    highest_risk_month: "July",
    hotspot_score: 99.5,
    hotspot_tier: "Critical",
    primary_source: "Highway Police Maharashtra & MSRDC Audit",
    dominant_vehicle: "Multi-Axle Freight Truck & Private Passenger Car"
  },
  {
    location_id: "loc-mh-pune-navale-bridge",
    road_name: "NH-48 Mumbai-Bengaluru Highway (Navale Bridge Pune Bypass)",
    road_number: "NH-48",
    city: "Pune",
    locality: "Katraj New Tunnel to Navale Bridge Slope (Km 824)",
    latitude: 18.4592,
    longitude: 73.8184,
    road_type: "National Highway",
    state_id: "state-mh",
    state_name: "Maharashtra",
    state_code: "MH",
    district_id: "dist-pune",
    district_name: "Pune",
    total_accidents: 195,
    fatal_accidents: 84,
    total_deaths: 122,
    total_injuries: 310,
    total_critical_injuries: 88,
    last_accident_date: "2026-08-27",
    dominant_cause: "Continuous Downhill Gradient with Neutral Gear Coasting",
    dominant_type: "Multi-Vehicle Pileup",
    highest_risk_month: "November",
    hotspot_score: 99.9,
    hotspot_tier: "Critical",
    primary_source: "Pune Traffic Police & MoRTH Special Taskforce",
    dominant_vehicle: "Heavy Overloaded Container Truck & Multiple Trailing Cars"
  },
  {
    location_id: "loc-mh-samruddhi-buldhana",
    road_name: "Samruddhi Mahamarg (Mehkar-Karanja Lad Stretch Km 340)",
    road_number: "Samruddhi Exp",
    city: "Buldhana",
    locality: "Pimpalkhuta Tunnel Cut & Wildlife Corridor",
    latitude: 20.3412,
    longitude: 77.1214,
    road_type: "Expressway",
    state_id: "state-mh",
    state_name: "Maharashtra",
    state_code: "MH",
    district_id: "dist-buldhana",
    district_name: "Buldhana",
    total_accidents: 152,
    fatal_accidents: 68,
    total_deaths: 106,
    total_injuries: 235,
    total_critical_injuries: 64,
    last_accident_date: "2026-08-18",
    dominant_cause: "Highway Hypnosis at 120 km/h & Tyre Delamination",
    dominant_type: "Rollover / Overturning",
    highest_risk_month: "May",
    hotspot_score: 97.4,
    hotspot_tier: "Critical",
    primary_source: "Maharashtra Highway Safety Patrol (HSP)",
    dominant_vehicle: "Interstate AC Sleeper Bus & High-Speed SUV"
  },
  {
    location_id: "loc-mh-kasara-ghat",
    road_name: "Mumbai-Nashik Highway (Kasara Ghat / Thal Ghat)",
    road_number: "NH-160",
    city: "Thane",
    locality: "Bhatsa River Valley Descent Km 118",
    latitude: 19.6512,
    longitude: 73.4812,
    road_type: "National Highway",
    state_id: "state-mh",
    state_name: "Maharashtra",
    state_code: "MH",
    district_id: "dist-thane",
    district_name: "Thane",
    total_accidents: 140,
    fatal_accidents: 60,
    total_deaths: 88,
    total_injuries: 215,
    total_critical_injuries: 58,
    last_accident_date: "2026-08-11",
    dominant_cause: "Steep Hairpin Curves & Heavy Freight Brake Failure",
    dominant_type: "Rollover / Overturning",
    highest_risk_month: "August",
    hotspot_score: 94.7,
    hotspot_tier: "Critical",
    primary_source: "MoRTH National Blackspot Master",
    dominant_vehicle: "Heavy Freight Dumper & Agricultural Produce Truck"
  },
  {
    location_id: "loc-mh-mumbai-chedda-nagar",
    road_name: "Eastern Express Highway (Chedda Nagar Junction Ghatkopar)",
    road_number: "EEH-Mumbai",
    city: "Mumbai",
    locality: "Santacruz-Chembur Link Road Flyover Fork",
    latitude: 19.0682,
    longitude: 72.9012,
    road_type: "City Arterial Road / Ring Road",
    state_id: "state-mh",
    state_name: "Maharashtra",
    state_code: "MH",
    district_id: "dist-mumbai-suburban",
    district_name: "Mumbai Suburban",
    total_accidents: 122,
    fatal_accidents: 41,
    total_deaths: 48,
    total_injuries: 182,
    total_critical_injuries: 36,
    last_accident_date: "2026-08-03",
    dominant_cause: "Blind Merging of Multi-tier Flyovers & Speeding",
    dominant_type: "Side Impact / T-Bone",
    highest_risk_month: "October",
    hotspot_score: 88.1,
    hotspot_tier: "High",
    primary_source: "Mumbai Traffic Police (MTP)",
    dominant_vehicle: "BEST City Bus & Two-Wheeler"
  },

  // --------------------------------------------------------------------------
  // GUJARAT
  // --------------------------------------------------------------------------
  {
    location_id: "loc-gj-ne1-nadiad-anand",
    road_name: "National Expressway 1 (Ahmedabad-Vadodara Expressway)",
    road_number: "NE-1",
    city: "Kheda",
    locality: "Nadiad Toll Interchange Km 52",
    latitude: 22.6812,
    longitude: 72.8912,
    road_type: "Expressway",
    state_id: "state-gj",
    state_name: "Gujarat",
    state_code: "GJ",
    district_id: "dist-kheda",
    district_name: "Kheda",
    total_accidents: 136,
    fatal_accidents: 58,
    total_deaths: 86,
    total_injuries: 210,
    total_critical_injuries: 54,
    last_accident_date: "2026-08-22",
    dominant_cause: "High Velocity Rear Impacts into Broken Down Trucks",
    dominant_type: "Rear-end Collision",
    highest_risk_month: "January",
    hotspot_score: 95.3,
    hotspot_tier: "Critical",
    primary_source: "Gujarat Police Traffic Branch & NHAI",
    dominant_vehicle: "Chemical Tanker & Passenger Sedan"
  },
  {
    location_id: "loc-gj-surat-kamrej-nh48",
    road_name: "NH-48 Delhi-Mumbai Golden Quadrilateral (Kamrej Surat)",
    road_number: "NH-48",
    city: "Surat",
    locality: "Kamrej Toll Plaza & Industrial Corridor",
    latitude: 21.2812,
    longitude: 72.9612,
    road_type: "National Highway",
    state_id: "state-gj",
    state_name: "Gujarat",
    state_code: "GJ",
    district_id: "dist-surat",
    district_name: "Surat",
    total_accidents: 162,
    fatal_accidents: 67,
    total_deaths: 94,
    total_injuries: 250,
    total_critical_injuries: 64,
    last_accident_date: "2026-08-16",
    dominant_cause: "Industrial Freight Overcrowding & Textile Logistics",
    dominant_type: "Side Impact / T-Bone",
    highest_risk_month: "March",
    hotspot_score: 96.8,
    hotspot_tier: "Critical",
    primary_source: "MoRTH National Blackspot Master",
    dominant_vehicle: "Multi-Axle Textile Lorry & Auto-Rickshaw"
  },
  {
    location_id: "loc-gj-ahmedabad-iskcon",
    road_name: "Sarkhej-Gandhinagar (SG) Highway Iskcon Flyover",
    road_number: "SH-41 / SG Highway",
    city: "Ahmedabad",
    locality: "Iskcon Crossroads Flyover Crest",
    latitude: 23.0289,
    longitude: 72.5067,
    road_type: "City Arterial Road / Ring Road",
    state_id: "state-gj",
    state_name: "Gujarat",
    state_code: "GJ",
    district_id: "dist-ahmedabad",
    district_name: "Ahmedabad",
    total_accidents: 115,
    fatal_accidents: 44,
    total_deaths: 59,
    total_injuries: 168,
    total_critical_injuries: 39,
    last_accident_date: "2026-08-07",
    dominant_cause: "Midnight Supercar Overspeeding into Accident Crowd",
    dominant_type: "Hit and Run / Pedestrian",
    highest_risk_month: "July",
    hotspot_score: 91.8,
    hotspot_tier: "Critical",
    primary_source: "Ahmedabad Traffic Police Safety Audit",
    dominant_vehicle: "High-End Luxury Car & Bystander Pedestrians"
  },

  // --------------------------------------------------------------------------
  // MADHYA PRADESH
  // --------------------------------------------------------------------------
  {
    location_id: "loc-mp-indore-bypass-bicholi",
    road_name: "Indore Bypass Highway (Bicholi Mardana Flyover)",
    road_number: "NH-52",
    city: "Indore",
    locality: "Bicholi Mardana Ring Road Junction Km 12",
    latitude: 22.7124,
    longitude: 75.9212,
    road_type: "National Highway",
    state_id: "state-mp",
    state_name: "Madhya Pradesh",
    state_code: "MP",
    district_id: "dist-indore",
    district_name: "Indore",
    total_accidents: 145,
    fatal_accidents: 61,
    total_deaths: 89,
    total_injuries: 225,
    total_critical_injuries: 57,
    last_accident_date: "2026-08-24",
    dominant_cause: "Heavy Grain Logistics Trucks Entering City Ring",
    dominant_type: "Side Impact / T-Bone",
    highest_risk_month: "November",
    hotspot_score: 96.1,
    hotspot_tier: "Critical",
    primary_source: "MP Police PTRI Road Safety Cell",
    dominant_vehicle: "Agricultural Freight Truck & Two-Wheeler"
  },
  {
    location_id: "loc-mp-bhopal-hoshangabad-misrod",
    road_name: "Bhopal-Hoshangabad 6-Lane Highway (Misrod Curve)",
    road_number: "NH-46",
    city: "Bhopal",
    locality: "Misrod Railway Crossing & BRTS Flyover Cut",
    latitude: 23.1612,
    longitude: 77.4612,
    road_type: "National Highway",
    state_id: "state-mp",
    state_name: "Madhya Pradesh",
    state_code: "MP",
    district_id: "dist-bhopal",
    district_name: "Bhopal",
    total_accidents: 120,
    fatal_accidents: 48,
    total_deaths: 68,
    total_injuries: 180,
    total_critical_injuries: 43,
    last_accident_date: "2026-08-02",
    dominant_cause: "High-Speed Commercial Buses Overtaking on Wrong Lane",
    dominant_type: "Head-on Collision",
    highest_risk_month: "December",
    hotspot_score: 90.7,
    hotspot_tier: "Critical",
    primary_source: "Bhopal City Police",
    dominant_vehicle: "Inter-District Passenger Bus & Motorbike"
  },

  // --------------------------------------------------------------------------
  // GOA & CHHATTISGARH
  // --------------------------------------------------------------------------
  {
    location_id: "loc-ga-zuari-bridge-nh66",
    road_name: "NH-66 Mumbai-Goa-Kochi (New Zuari Bridge Approach Cortalim)",
    road_number: "NH-66",
    city: "South Goa",
    locality: "Cortalim Roundabout & Cable-Stayed Approach",
    latitude: 15.3982,
    longitude: 73.9124,
    road_type: "National Highway",
    state_id: "state-ga",
    state_name: "Goa",
    state_code: "GA",
    district_id: "dist-south-goa",
    district_name: "South Goa",
    total_accidents: 86,
    fatal_accidents: 32,
    total_deaths: 41,
    total_injuries: 130,
    total_critical_injuries: 29,
    last_accident_date: "2026-07-25",
    dominant_cause: "Tourist Rental Cars Drunk Driving at Night",
    dominant_type: "Head-on Collision",
    highest_risk_month: "December",
    hotspot_score: 84.1,
    hotspot_tier: "High",
    primary_source: "Goa Traffic Police Safety Cell",
    dominant_vehicle: "Tourist Rental Thar / Scooter & Local Bus"
  },
  {
    location_id: "loc-cg-raipur-bhilai-nh53",
    road_name: "NH-53 Great Eastern Road (Bhilai Steel Plant - Durg Bypass)",
    road_number: "NH-53",
    city: "Durg",
    locality: "Power House Bhilai Flyover Junction",
    latitude: 21.2124,
    longitude: 81.3812,
    road_type: "National Highway",
    state_id: "state-cg",
    state_name: "Chhattisgarh",
    state_code: "CG",
    district_id: "dist-durg",
    district_name: "Durg",
    total_accidents: 134,
    fatal_accidents: 56,
    total_deaths: 79,
    total_injuries: 205,
    total_critical_injuries: 51,
    last_accident_date: "2026-08-14",
    dominant_cause: "Heavy Steel Trailer Ingress with Cyclists & Pedestrians",
    dominant_type: "Hit and Run / Pedestrian",
    highest_risk_month: "February",
    hotspot_score: 93.5,
    hotspot_tier: "Critical",
    primary_source: "Chhattisgarh Police Highway Cell",
    dominant_vehicle: "Steel Coil Trailer & Bicycle / Two-Wheeler"
  }
];
