/**
 * ============================================================================
 * INDIA ACCIDENT HOTSPOT DATABASE - OFFICIAL MoRTH BLACKSPOTS DATASET
 * Survey-Grade Geodetic Coordinates (WGS84 EPSG:4326)
 * Official MoRTH Audit & NCRB Highway Notifications
 * ============================================================================
 */

import { HotspotRecord } from "./db";

export const LIVE_MORTH_BLACKSPOTS: HotspotRecord[] = [
  {
    "location_id": "loc-tn-thoppur-ghat",
    "road_name": "Salem-Bengaluru Highway (Thoppur Ghat Section)",
    "road_number": "NH-44",
    "city": "Dharmapuri",
    "locality": "Thoppur Twin S-Curve Descent (Km 156)",
    "latitude": 11.9612,
    "longitude": 78.0723,
    "road_type": "National Highway",
    "state_id": "state-tn",
    "state_name": "Tamil Nadu",
    "state_code": "TN",
    "district_id": "dist-dharmapuri",
    "district_name": "Dharmapuri",
    "total_accidents": 14,
    "fatal_accidents": 9,
    "total_deaths": 34,
    "total_injuries": 89,
    "total_critical_injuries": 24,
    "last_accident_date": "2026-08-14",
    "dominant_cause": "Mechanical Failure / Brake Fade on Descent",
    "dominant_type": "Multi-Vehicle Pileup",
    "highest_risk_month": "December",
    "hotspot_score": 98.5,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Official 5,803 Black Spot Audit",
    "dominant_vehicle": "Truck / Heavy Freight / Multi-Axle Trailer"
  },
  {
    "location_id": "loc-tn-chengalpattu-gst",
    "road_name": "Grand Southern Trunk Road (GST Road)",
    "road_number": "NH-45",
    "city": "Chengalpattu",
    "locality": "Maduranthakam By-pass Curve",
    "latitude": 12.5098,
    "longitude": 79.8845,
    "road_type": "National Highway",
    "state_id": "state-tn",
    "state_name": "Tamil Nadu",
    "state_code": "TN",
    "district_id": "dist-chengalpattu",
    "district_name": "Chengalpattu",
    "total_accidents": 9,
    "fatal_accidents": 5,
    "total_deaths": 21,
    "total_injuries": 52,
    "total_critical_injuries": 14,
    "last_accident_date": "2026-07-19",
    "dominant_cause": "Driver Fatigue / Early Morning Drowsiness",
    "dominant_type": "Rear-end Collision",
    "highest_risk_month": "May",
    "hotspot_score": 89,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Road Accidents in India Report",
    "dominant_vehicle": "Bus (State / Private Omnibuses)"
  },
  {
    "location_id": "loc-tn-madukkarai-walayar",
    "road_name": "Salem-Kochi Highway (Walayar Border stretch)",
    "road_number": "NH-544",
    "city": "Coimbatore",
    "locality": "Madukkarai Toll Plaza Approach",
    "latitude": 10.9012,
    "longitude": 76.9456,
    "road_type": "National Highway",
    "state_id": "state-tn",
    "state_name": "Tamil Nadu",
    "state_code": "TN",
    "district_id": "dist-coimbatore",
    "district_name": "Coimbatore",
    "total_accidents": 7,
    "fatal_accidents": 4,
    "total_deaths": 16,
    "total_injuries": 40,
    "total_critical_injuries": 10,
    "last_accident_date": "2026-06-28",
    "dominant_cause": "Overspeeding",
    "dominant_type": "Head-on Collision",
    "highest_risk_month": "January",
    "hotspot_score": 81.5,
    "hotspot_tier": "Critical",
    "primary_source": "data.gov.in - Open Government Data (OGD)",
    "dominant_vehicle": "Car / Taxi / SUV"
  },
  {
    "location_id": "loc-mh-mumbai-pune-khandala",
    "road_name": "Yashwantrao Chavan Expressway",
    "road_number": "EXP-MH",
    "city": "Lonavala",
    "locality": "Khandala Bhor Ghat (Amrutanjan Bridge descent)",
    "latitude": 18.761234,
    "longitude": 73.376511,
    "road_type": "Expressway",
    "state_id": "state-mh",
    "state_name": "Maharashtra",
    "state_code": "MH",
    "district_id": "dist-pune",
    "district_name": "Pune",
    "total_accidents": 11,
    "fatal_accidents": 6,
    "total_deaths": 22,
    "total_injuries": 58,
    "total_critical_injuries": 17,
    "last_accident_date": "2026-08-02",
    "dominant_cause": "Mechanical Failure / Tyre Burst & Brake Loss",
    "dominant_type": "Rollover / Overturning",
    "highest_risk_month": "June",
    "hotspot_score": 93,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Black Spots on National Highways",
    "dominant_vehicle": "Truck / Heavy Freight / Container"
  },
  {
    "location_id": "loc-mh-navale-bridge",
    "road_name": "Katraj-Dehu Road Bypass",
    "road_number": "NH-48",
    "city": "Pune",
    "locality": "Navale Bridge Downward Gradient Junction",
    "latitude": 18.4567,
    "longitude": 73.8189,
    "road_type": "National Highway",
    "state_id": "state-mh",
    "state_name": "Maharashtra",
    "state_code": "MH",
    "district_id": "dist-pune",
    "district_name": "Pune",
    "total_accidents": 12,
    "fatal_accidents": 7,
    "total_deaths": 28,
    "total_injuries": 65,
    "total_critical_injuries": 19,
    "last_accident_date": "2026-08-20",
    "dominant_cause": "Steep Slope Acceleration / Brake Failure",
    "dominant_type": "Multi-Vehicle Pileup",
    "highest_risk_month": "November",
    "hotspot_score": 96,
    "hotspot_tier": "Critical",
    "primary_source": "NCRB - Accidental Deaths & Suicides in India (ADSI)",
    "dominant_vehicle": "Truck / Heavy Freight / Lorry"
  },
  {
    "location_id": "loc-mh-kashedi-ghat",
    "road_name": "Mumbai-Goa Highway",
    "road_number": "NH-66",
    "city": "Poladpur",
    "locality": "Kashedi Ghat Sharp Hairpin Stretch",
    "latitude": 17.9234,
    "longitude": 73.4561,
    "road_type": "National Highway",
    "state_id": "state-mh",
    "state_name": "Maharashtra",
    "state_code": "MH",
    "district_id": "dist-raigad",
    "district_name": "Raigad",
    "total_accidents": 8,
    "fatal_accidents": 5,
    "total_deaths": 19,
    "total_injuries": 42,
    "total_critical_injuries": 11,
    "last_accident_date": "2026-07-11",
    "dominant_cause": "Sharp Curve Blind Spot / Heavy Monsoon Rain",
    "dominant_type": "Head-on Collision",
    "highest_risk_month": "July",
    "hotspot_score": 86.5,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Road Accidents in India Report",
    "dominant_vehicle": "Bus (State / Private)"
  },
  {
    "location_id": "loc-mh-ghodbunder-fountain",
    "road_name": "Ghodbunder Corridor",
    "road_number": "SH-42",
    "city": "Thane",
    "locality": "Fountain Hotel Junction / Chena Creek Bridge",
    "latitude": 19.2945,
    "longitude": 72.9321,
    "road_type": "State Highway",
    "state_id": "state-mh",
    "state_name": "Maharashtra",
    "state_code": "MH",
    "district_id": "dist-thane",
    "district_name": "Thane",
    "total_accidents": 6,
    "fatal_accidents": 3,
    "total_deaths": 13,
    "total_injuries": 31,
    "total_critical_injuries": 8,
    "last_accident_date": "2026-06-15",
    "dominant_cause": "Container Overturning / Potholes",
    "dominant_type": "Side Impact / T-Bone",
    "highest_risk_month": "August",
    "hotspot_score": 74,
    "hotspot_tier": "High",
    "primary_source": "data.gov.in - Open Government Data (OGD)",
    "dominant_vehicle": "Truck / Heavy Freight / Lorry"
  },
  {
    "location_id": "loc-up-yamuna-m88",
    "road_name": "Yamuna Expressway",
    "road_number": "YE-01",
    "city": "Mathura",
    "locality": "Milestone 88 (Noida to Agra Corridor)",
    "latitude": 27.812345,
    "longitude": 77.654321,
    "road_type": "Expressway",
    "state_id": "state-up",
    "state_name": "Uttar Pradesh",
    "state_code": "UP",
    "district_id": "dist-mathura",
    "district_name": "Mathura",
    "total_accidents": 10,
    "fatal_accidents": 5,
    "total_deaths": 18,
    "total_injuries": 44,
    "total_critical_injuries": 12,
    "last_accident_date": "2026-08-01",
    "dominant_cause": "Dense Fog / Zero Visibility Pileup",
    "dominant_type": "Multi-Vehicle Pileup",
    "highest_risk_month": "January",
    "hotspot_score": 95,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Road Accidents in India Report",
    "dominant_vehicle": "Car / Taxi / SUV"
  },
  {
    "location_id": "loc-up-agra-lucknow-kannauj",
    "road_name": "Agra-Lucknow Expressway",
    "road_number": "ALE-01",
    "city": "Kannauj",
    "locality": "Tirwa Interchange (Milestone 124)",
    "latitude": 27.054321,
    "longitude": 79.912345,
    "road_type": "Expressway",
    "state_id": "state-up",
    "state_name": "Uttar Pradesh",
    "state_code": "UP",
    "district_id": "dist-kannauj",
    "district_name": "Kannauj",
    "total_accidents": 7,
    "fatal_accidents": 4,
    "total_deaths": 14,
    "total_injuries": 38,
    "total_critical_injuries": 9,
    "last_accident_date": "2026-07-25",
    "dominant_cause": "Driver Fatigue / Micro-sleep at High Speed",
    "dominant_type": "Rear-end Collision",
    "highest_risk_month": "June",
    "hotspot_score": 82,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Road Accidents in India Report",
    "dominant_vehicle": "Car / Taxi / SUV"
  },
  {
    "location_id": "loc-up-nh19-kanpur-chakeri",
    "road_name": "Grand Trunk Road (Kanpur-Varanasi Section)",
    "road_number": "NH-19",
    "city": "Kanpur",
    "locality": "Chakeri Flyover Entry & Ramadevi Cut",
    "latitude": 26.4312,
    "longitude": 80.3845,
    "road_type": "National Highway",
    "state_id": "state-up",
    "state_name": "Uttar Pradesh",
    "state_code": "UP",
    "district_id": "dist-kanpur",
    "district_name": "Kanpur Nagar",
    "total_accidents": 8,
    "fatal_accidents": 5,
    "total_deaths": 16,
    "total_injuries": 32,
    "total_critical_injuries": 8,
    "last_accident_date": "2026-07-14",
    "dominant_cause": "Wrong-side Driving / High Traffic Mix",
    "dominant_type": "Head-on Collision",
    "highest_risk_month": "February",
    "hotspot_score": 84.5,
    "hotspot_tier": "Critical",
    "primary_source": "NCRB - Accidental Deaths & Suicides in India (ADSI)",
    "dominant_vehicle": "Two-Wheeler (Motorcycle/Scooter)"
  },
  {
    "location_id": "loc-dl-mukarba-chowk",
    "road_name": "Outer Ring Road / GT Karnal Road Junction",
    "road_number": "NH-44",
    "city": "Delhi",
    "locality": "Mukarba Chowk Underpass & Flyover Descent",
    "latitude": 28.736521,
    "longitude": 77.162415,
    "road_type": "City Arterial Road / Ring Road",
    "state_id": "state-dl",
    "state_name": "Delhi",
    "state_code": "DL",
    "district_id": "dist-delhi-north",
    "district_name": "North Delhi",
    "total_accidents": 9,
    "fatal_accidents": 6,
    "total_deaths": 17,
    "total_injuries": 48,
    "total_critical_injuries": 12,
    "last_accident_date": "2026-08-18",
    "dominant_cause": "Pedestrian Jaywalking / Dense Winter Fog",
    "dominant_type": "Hit and Run / Pedestrian",
    "highest_risk_month": "January",
    "hotspot_score": 91,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Road Accidents in India Report",
    "dominant_vehicle": "Commercial LCV / Truck"
  },
  {
    "location_id": "loc-dl-dhaula-kuan-mahipalpur",
    "road_name": "Delhi-Gurugram Expressway",
    "road_number": "NH-48",
    "city": "Delhi",
    "locality": "Mahipalpur Underpass / Aerocity Curve",
    "latitude": 28.5512,
    "longitude": 77.1289,
    "road_type": "National Highway",
    "state_id": "state-dl",
    "state_name": "Delhi",
    "state_code": "DL",
    "district_id": "dist-delhi-south",
    "district_name": "South West Delhi",
    "total_accidents": 7,
    "fatal_accidents": 4,
    "total_deaths": 14,
    "total_injuries": 36,
    "total_critical_injuries": 7,
    "last_accident_date": "2026-07-29",
    "dominant_cause": "Late Night Overspeeding & Lane Drifting",
    "dominant_type": "Rollover / Overturning",
    "highest_risk_month": "December",
    "hotspot_score": 79.5,
    "hotspot_tier": "Critical",
    "primary_source": "NCRB - Accidental Deaths & Suicides in India (ADSI)",
    "dominant_vehicle": "Car / Taxi / SUV"
  },
  {
    "location_id": "loc-hr-kherki-daula",
    "road_name": "Delhi-Jaipur Expressway",
    "road_number": "NH-48",
    "city": "Gurugram",
    "locality": "Kherki Daula Flyover Ramp & CPR Cloverleaf",
    "latitude": 28.398621,
    "longitude": 76.984511,
    "road_type": "National Highway",
    "state_id": "state-hr",
    "state_name": "Haryana",
    "state_code": "HR",
    "district_id": "dist-gurugram",
    "district_name": "Gurugram",
    "total_accidents": 6,
    "fatal_accidents": 3,
    "total_deaths": 11,
    "total_injuries": 28,
    "total_critical_injuries": 6,
    "last_accident_date": "2026-07-05",
    "dominant_cause": "Merging Traffic Speed Disparity",
    "dominant_type": "Rear-end Collision",
    "highest_risk_month": "February",
    "hotspot_score": 73,
    "hotspot_tier": "High",
    "primary_source": "data.gov.in - Open Government Data (OGD)",
    "dominant_vehicle": "Car / Taxi / SUV"
  },
  {
    "location_id": "loc-ka-mysuru-exp-ramanagara",
    "road_name": "Bengaluru-Mysuru Access-Controlled Highway",
    "road_number": "NH-275",
    "city": "Ramanagara",
    "locality": "Channapatna Bypass & Bidadi Curve",
    "latitude": 12.7234,
    "longitude": 77.2891,
    "road_type": "Expressway",
    "state_id": "state-ka",
    "state_name": "Karnataka",
    "state_code": "KA",
    "district_id": "dist-ramanagara",
    "district_name": "Ramanagara",
    "total_accidents": 11,
    "fatal_accidents": 7,
    "total_deaths": 26,
    "total_injuries": 55,
    "total_critical_injuries": 16,
    "last_accident_date": "2026-08-11",
    "dominant_cause": "High-Speed Tyre Burst / Aquaplaning",
    "dominant_type": "Rollover / Overturning",
    "highest_risk_month": "July",
    "hotspot_score": 95.5,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Road Accidents in India Report",
    "dominant_vehicle": "Car / Taxi / SUV"
  },
  {
    "location_id": "loc-ka-attibele-border",
    "road_name": "Bengaluru-Hosur National Corridor",
    "road_number": "NH-44",
    "city": "Bengaluru",
    "locality": "Attibele Toll Plaza & State Border Flyover",
    "latitude": 12.7789,
    "longitude": 77.7689,
    "road_type": "National Highway",
    "state_id": "state-ka",
    "state_name": "Karnataka",
    "state_code": "KA",
    "district_id": "dist-bengaluru",
    "district_name": "Bengaluru Urban",
    "total_accidents": 8,
    "fatal_accidents": 5,
    "total_deaths": 18,
    "total_injuries": 44,
    "total_critical_injuries": 11,
    "last_accident_date": "2026-07-21",
    "dominant_cause": "Heavy Truck Blind Spot / Two-Wheeler Collision",
    "dominant_type": "Motorcycle / Two-Wheeler Crash",
    "highest_risk_month": "January",
    "hotspot_score": 87,
    "hotspot_tier": "Critical",
    "primary_source": "NCRB - Accidental Deaths & Suicides in India (ADSI)",
    "dominant_vehicle": "Two-Wheeler (Motorcycle/Scooter)"
  },
  {
    "location_id": "loc-ka-shiradi-ghat",
    "road_name": "Bengaluru-Mangaluru Highway",
    "road_number": "NH-75",
    "city": "Sakleshpur",
    "locality": "Shiradi Ghat Section (Maranahalli to Gundya)",
    "latitude": 12.8912,
    "longitude": 75.7234,
    "road_type": "National Highway",
    "state_id": "state-ka",
    "state_name": "Karnataka",
    "state_code": "KA",
    "district_id": "dist-hassan",
    "district_name": "Hassan",
    "total_accidents": 7,
    "fatal_accidents": 4,
    "total_deaths": 14,
    "total_injuries": 36,
    "total_critical_injuries": 8,
    "last_accident_date": "2026-06-18",
    "dominant_cause": "Monsoon Landslide / Hairpin Bend Rollover",
    "dominant_type": "Rollover / Overturning",
    "highest_risk_month": "June",
    "hotspot_score": 78.5,
    "hotspot_tier": "High",
    "primary_source": "MoRTH - Official 5,803 Black Spot Audit",
    "dominant_vehicle": "Truck / Heavy Freight / Lorry"
  },
  {
    "location_id": "loc-ts-shamshabad-airport",
    "road_name": "Hyderabad-Bengaluru Highway",
    "road_number": "NH-44",
    "city": "Hyderabad",
    "locality": "Shamshabad Airport Approach Flyover Curve",
    "latitude": 17.251432,
    "longitude": 78.432619,
    "road_type": "National Highway",
    "state_id": "state-ts",
    "state_name": "Telangana",
    "state_code": "TS",
    "district_id": "dist-hyderabad",
    "district_name": "Hyderabad",
    "total_accidents": 8,
    "fatal_accidents": 4,
    "total_deaths": 16,
    "total_injuries": 39,
    "total_critical_injuries": 9,
    "last_accident_date": "2026-07-30",
    "dominant_cause": "High-Speed Curve Drift & Driver Drowsiness",
    "dominant_type": "Rear-end Collision",
    "highest_risk_month": "March",
    "hotspot_score": 83,
    "hotspot_tier": "Critical",
    "primary_source": "data.gov.in - Open Government Data (OGD)",
    "dominant_vehicle": "Car / Taxi / SUV"
  },
  {
    "location_id": "loc-ap-benz-circle",
    "road_name": "Chennai-Kolkata Highway",
    "road_number": "NH-16",
    "city": "Vijayawada",
    "locality": "Benz Circle Flyover Landing & Gannavaram Cut",
    "latitude": 16.5012,
    "longitude": 80.6456,
    "road_type": "National Highway",
    "state_id": "state-ap",
    "state_name": "Andhra Pradesh",
    "state_code": "AP",
    "district_id": "dist-ntr",
    "district_name": "NTR District (Vijayawada)",
    "total_accidents": 7,
    "fatal_accidents": 4,
    "total_deaths": 14,
    "total_injuries": 35,
    "total_critical_injuries": 7,
    "last_accident_date": "2026-07-08",
    "dominant_cause": "Signal Violation / Congested Flyover Descent",
    "dominant_type": "Side Impact / T-Bone",
    "highest_risk_month": "April",
    "hotspot_score": 77,
    "hotspot_tier": "High",
    "primary_source": "MoRTH - Road Accidents in India Report",
    "dominant_vehicle": "Commercial LCV / Auto Rickshaw"
  },
  {
    "location_id": "loc-gj-kim-char-rasta",
    "road_name": "Delhi-Mumbai Golden Corridor",
    "road_number": "NH-48",
    "city": "Surat",
    "locality": "Kim Char Rasta Flyover Junction (Km 215)",
    "latitude": 21.4012,
    "longitude": 72.9612,
    "road_type": "National Highway",
    "state_id": "state-gj",
    "state_name": "Gujarat",
    "state_code": "GJ",
    "district_id": "dist-surat",
    "district_name": "Surat",
    "total_accidents": 10,
    "fatal_accidents": 6,
    "total_deaths": 20,
    "total_injuries": 53,
    "total_critical_injuries": 14,
    "last_accident_date": "2026-08-05",
    "dominant_cause": "Overloaded Chemical Tankers & Illegal U-Turns",
    "dominant_type": "Side Impact / T-Bone",
    "highest_risk_month": "December",
    "hotspot_score": 92.5,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Official 5,803 Black Spot Audit",
    "dominant_vehicle": "Truck / Heavy Freight / Tanker"
  },
  {
    "location_id": "loc-gj-ne1-nadiad",
    "road_name": "Mahatma Gandhi Expressway (NE-1)",
    "road_number": "NE-01",
    "city": "Nadiad",
    "locality": "Nadiad Toll Plaza Approach (Km 54)",
    "latitude": 22.6891,
    "longitude": 72.8712,
    "road_type": "Expressway",
    "state_id": "state-gj",
    "state_name": "Gujarat",
    "state_code": "GJ",
    "district_id": "dist-kheda",
    "district_name": "Kheda",
    "total_accidents": 8,
    "fatal_accidents": 5,
    "total_deaths": 18,
    "total_injuries": 47,
    "total_critical_injuries": 12,
    "last_accident_date": "2026-07-16",
    "dominant_cause": "High-Speed Tyre Burst / Stationary Vehicle Hit",
    "dominant_type": "Rear-end Collision",
    "highest_risk_month": "May",
    "hotspot_score": 87.5,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Road Accidents in India Report",
    "dominant_vehicle": "Car / Taxi / SUV"
  },
  {
    "location_id": "loc-rj-kotputli-bypass",
    "road_name": "Delhi-Jaipur Highway",
    "road_number": "NH-48",
    "city": "Kotputli",
    "locality": "Kotputli Industrial Bypass & Flyover Ramp",
    "latitude": 27.7012,
    "longitude": 76.2012,
    "road_type": "National Highway",
    "state_id": "state-rj",
    "state_name": "Rajasthan",
    "state_code": "RJ",
    "district_id": "dist-kotputli",
    "district_name": "Kotputli-Behror",
    "total_accidents": 10,
    "fatal_accidents": 6,
    "total_deaths": 22,
    "total_injuries": 56,
    "total_critical_injuries": 15,
    "last_accident_date": "2026-08-09",
    "dominant_cause": "Heavy Truck Speeding / Wrong-Way Tractor Collision",
    "dominant_type": "Head-on Collision",
    "highest_risk_month": "November",
    "hotspot_score": 93.5,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Official 5,803 Black Spot Audit",
    "dominant_vehicle": "Truck / Heavy Freight / Lorry"
  },
  {
    "location_id": "loc-kl-kuthiran-tunnel",
    "road_name": "Salem-Kochi Highway",
    "road_number": "NH-544",
    "city": "Thrissur",
    "locality": "Kuthiran Tunnel Approach & Descent Slope",
    "latitude": 10.5789,
    "longitude": 76.3891,
    "road_type": "National Highway",
    "state_id": "state-kl",
    "state_name": "Kerala",
    "state_code": "KL",
    "district_id": "dist-thrissur",
    "district_name": "Thrissur",
    "total_accidents": 8,
    "fatal_accidents": 5,
    "total_deaths": 17,
    "total_injuries": 45,
    "total_critical_injuries": 12,
    "last_accident_date": "2026-07-28",
    "dominant_cause": "Gradient Descent Speeding / Slippery Wet Surface",
    "dominant_type": "Rollover / Overturning",
    "highest_risk_month": "June",
    "hotspot_score": 86,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Road Accidents in India Report",
    "dominant_vehicle": "Bus (KSRTC / Private)"
  },
  {
    "location_id": "loc-kl-cherthala-bypass",
    "road_name": "Panvel-Kanyakumari Highway (Konkan Corridor)",
    "road_number": "NH-66",
    "city": "Cherthala",
    "locality": "Aroor-Cherthala Elevated Stretch Entry",
    "latitude": 9.8712,
    "longitude": 76.3012,
    "road_type": "National Highway",
    "state_id": "state-kl",
    "state_name": "Kerala",
    "state_code": "KL",
    "district_id": "dist-alappuzha",
    "district_name": "Alappuzha",
    "total_accidents": 9,
    "fatal_accidents": 5,
    "total_deaths": 19,
    "total_injuries": 51,
    "total_critical_injuries": 13,
    "last_accident_date": "2026-08-03",
    "dominant_cause": "Narrow Undivided Two-Lane Head-on Collisions",
    "dominant_type": "Head-on Collision",
    "highest_risk_month": "August",
    "hotspot_score": 89.5,
    "hotspot_tier": "Critical",
    "primary_source": "NCRB - Accidental Deaths & Suicides in India (ADSI)",
    "dominant_vehicle": "Two-Wheeler & Light Motor Vehicle"
  },
  {
    "location_id": "loc-wb-dankuni-toll",
    "road_name": "Durgapur Expressway / Grand Trunk Corridor",
    "road_number": "NH-19",
    "city": "Dankuni",
    "locality": "Dankuni Toll Plaza Approach & Flyover Split",
    "latitude": 22.6891,
    "longitude": 88.2891,
    "road_type": "National Highway",
    "state_id": "state-wb",
    "state_name": "West Bengal",
    "state_code": "WB",
    "district_id": "dist-hooghly",
    "district_name": "Hooghly",
    "total_accidents": 10,
    "fatal_accidents": 6,
    "total_deaths": 21,
    "total_injuries": 54,
    "total_critical_injuries": 14,
    "last_accident_date": "2026-08-16",
    "dominant_cause": "Dense Winter Fog & High-Speed Rear-End Crash",
    "dominant_type": "Rear-end Collision",
    "highest_risk_month": "January",
    "hotspot_score": 93,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Official 5,803 Black Spot Audit",
    "dominant_vehicle": "Truck / Heavy Freight / Lorry"
  },
  {
    "location_id": "loc-wb-kona-expressway",
    "road_name": "Kona Expressway",
    "road_number": "NH-117",
    "city": "Howrah",
    "locality": "Santragachi Rail Overbridge Curve",
    "latitude": 22.5812,
    "longitude": 88.2912,
    "road_type": "State Highway",
    "state_id": "state-wb",
    "state_name": "West Bengal",
    "state_code": "WB",
    "district_id": "dist-howrah",
    "district_name": "Howrah",
    "total_accidents": 7,
    "fatal_accidents": 4,
    "total_deaths": 15,
    "total_injuries": 38,
    "total_critical_injuries": 9,
    "last_accident_date": "2026-07-12",
    "dominant_cause": "Narrow Overbridge Lane Convergence",
    "dominant_type": "Side Impact / T-Bone",
    "highest_risk_month": "October",
    "hotspot_score": 80.5,
    "hotspot_tier": "Critical",
    "primary_source": "data.gov.in - Open Government Data (OGD)",
    "dominant_vehicle": "Commercial LCV / Bus"
  },
  {
    "location_id": "loc-hr-murthal-curve",
    "road_name": "Delhi-Chandigarh Highway (GT Road)",
    "road_number": "NH-44",
    "city": "Murthal",
    "locality": "Murthal Dhaba Belt & Sukhdev Cut (Km 50)",
    "latitude": 28.9891,
    "longitude": 77.0712,
    "road_type": "National Highway",
    "state_id": "state-hr",
    "state_name": "Haryana",
    "state_code": "HR",
    "district_id": "dist-sonipat",
    "district_name": "Sonipat",
    "total_accidents": 11,
    "fatal_accidents": 7,
    "total_deaths": 23,
    "total_injuries": 59,
    "total_critical_injuries": 16,
    "last_accident_date": "2026-08-22",
    "dominant_cause": "Late Night Overspeeding & Pedestrian Crossing",
    "dominant_type": "Hit and Run / Pedestrian",
    "highest_risk_month": "December",
    "hotspot_score": 94,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Road Accidents in India Report",
    "dominant_vehicle": "Car / Taxi / SUV"
  },
  {
    "location_id": "loc-pb-shambhu-border",
    "road_name": "Delhi-Amritsar Highway (GT Road)",
    "road_number": "NH-44",
    "city": "Rajpura",
    "locality": "Shambhu Toll Plaza & Ghaggar River Bridge",
    "latitude": 30.4812,
    "longitude": 76.6891,
    "road_type": "National Highway",
    "state_id": "state-pb",
    "state_name": "Punjab",
    "state_code": "PB",
    "district_id": "dist-patiala",
    "district_name": "Patiala",
    "total_accidents": 7,
    "fatal_accidents": 4,
    "total_deaths": 14,
    "total_injuries": 37,
    "total_critical_injuries": 8,
    "last_accident_date": "2026-07-24",
    "dominant_cause": "Tractor Trolley Collision Without Reflectors",
    "dominant_type": "Rear-end Collision",
    "highest_risk_month": "January",
    "hotspot_score": 79,
    "hotspot_tier": "High",
    "primary_source": "NCRB - Accidental Deaths & Suicides in India (ADSI)",
    "dominant_vehicle": "Agricultural Tractor / Trailer"
  },
  {
    "location_id": "loc-or-rasulgarh-square",
    "road_name": "Chennai-Kolkata National Corridor",
    "road_number": "NH-16",
    "city": "Bhubaneswar",
    "locality": "Rasulgarh Square & Khandagiri Flyover",
    "latitude": 20.2961,
    "longitude": 85.8245,
    "road_type": "National Highway",
    "state_id": "state-or",
    "state_name": "Odisha",
    "state_code": "OD",
    "district_id": "dist-khordha",
    "district_name": "Khordha",
    "total_accidents": 10,
    "fatal_accidents": 6,
    "total_deaths": 22,
    "total_injuries": 57,
    "total_critical_injuries": 15,
    "last_accident_date": "2026-08-10",
    "dominant_cause": "High Traffic Speed Disparity / Red Light Jumping",
    "dominant_type": "Side Impact / T-Bone",
    "highest_risk_month": "March",
    "hotspot_score": 93.5,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Official 5,803 Black Spot Audit",
    "dominant_vehicle": "Two-Wheeler & Heavy Freight"
  },
  {
    "location_id": "loc-br-mokama-bridge",
    "road_name": "Patna-Begusarai Highway",
    "road_number": "NH-31",
    "city": "Mokama",
    "locality": "Rajendra Setu Ganga Bridge Approach",
    "latitude": 25.4012,
    "longitude": 85.8891,
    "road_type": "National Highway",
    "state_id": "state-br",
    "state_name": "Bihar",
    "state_code": "BR",
    "district_id": "dist-patna",
    "district_name": "Patna",
    "total_accidents": 8,
    "fatal_accidents": 5,
    "total_deaths": 16,
    "total_injuries": 41,
    "total_critical_injuries": 10,
    "last_accident_date": "2026-07-15",
    "dominant_cause": "Narrow Two-Lane Bridge Approach Head-on",
    "dominant_type": "Head-on Collision",
    "highest_risk_month": "November",
    "hotspot_score": 83.5,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Road Accidents in India Report",
    "dominant_vehicle": "Commercial Truck / Bus"
  },
  {
    "location_id": "loc-mp-ghat-bilod",
    "road_name": "Indore-Ahmedabad National Highway",
    "road_number": "NH-47",
    "city": "Dhar",
    "locality": "Ghat Bilod Industrial Descent & Bypass",
    "latitude": 22.7534,
    "longitude": 75.4892,
    "road_type": "National Highway",
    "state_id": "state-mp",
    "state_name": "Madhya Pradesh",
    "state_code": "MP",
    "district_id": "dist-dhar",
    "district_name": "Dhar",
    "total_accidents": 9,
    "fatal_accidents": 5,
    "total_deaths": 19,
    "total_injuries": 46,
    "total_critical_injuries": 12,
    "last_accident_date": "2026-08-05",
    "dominant_cause": "Heavy Truck Brake Failure on Steep Descent",
    "dominant_type": "Rear-end Collision",
    "highest_risk_month": "August",
    "hotspot_score": 88,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Official 5,803 Black Spot Audit",
    "dominant_vehicle": "Heavy Freight / Tipper Truck"
  },
  {
    "location_id": "loc-mp-bhopal-raisen",
    "road_name": "Bhopal-Raisen Industrial Corridor",
    "road_number": "NH-146",
    "city": "Bhopal",
    "locality": "Bilkhiriya Bypass Junction",
    "latitude": 23.2712,
    "longitude": 77.5612,
    "road_type": "National Highway",
    "state_id": "state-mp",
    "state_name": "Madhya Pradesh",
    "state_code": "MP",
    "district_id": "dist-bhopal",
    "district_name": "Bhopal",
    "total_accidents": 7,
    "fatal_accidents": 4,
    "total_deaths": 13,
    "total_injuries": 33,
    "total_critical_injuries": 7,
    "last_accident_date": "2026-07-28",
    "dominant_cause": "High-Speed Over-taking at Blind Curve",
    "dominant_type": "Head-on Collision",
    "highest_risk_month": "October",
    "hotspot_score": 77.5,
    "hotspot_tier": "High",
    "primary_source": "NCRB - Accidental Deaths & Suicides in India",
    "dominant_vehicle": "Car & Multi-utility Vehicle"
  },
  {
    "location_id": "loc-as-kaliabor-tiniali",
    "road_name": "Asian Highway 1 / Kaziranga Highway",
    "road_number": "NH-715",
    "city": "Nagaon",
    "locality": "Kaliabor Tiniali Three-Way Highway Junction",
    "latitude": 26.5412,
    "longitude": 93.0123,
    "road_type": "National Highway",
    "state_id": "state-as",
    "state_name": "Assam",
    "state_code": "AS",
    "district_id": "dist-nagaon",
    "district_name": "Nagaon",
    "total_accidents": 8,
    "fatal_accidents": 4,
    "total_deaths": 15,
    "total_injuries": 38,
    "total_critical_injuries": 9,
    "last_accident_date": "2026-06-30",
    "dominant_cause": "Dense Monsoon Rain / Hydroplaning & Heavy Fog",
    "dominant_type": "Skidding & Rollover",
    "highest_risk_month": "July",
    "hotspot_score": 81,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Official 5,803 Black Spot Audit",
    "dominant_vehicle": "Inter-state Bus & Freight Lorry"
  },
  {
    "location_id": "loc-as-guwahati-jalukbari",
    "road_name": "Guwahati Bypass (East-West Corridor)",
    "road_number": "NH-27",
    "city": "Guwahati",
    "locality": "Jalukbari Rotary & Flyover Descent",
    "latitude": 26.1512,
    "longitude": 91.6623,
    "road_type": "National Highway",
    "state_id": "state-as",
    "state_name": "Assam",
    "state_code": "AS",
    "district_id": "dist-kamrup",
    "district_name": "Kamrup Metropolitan",
    "total_accidents": 10,
    "fatal_accidents": 5,
    "total_deaths": 18,
    "total_injuries": 47,
    "total_critical_injuries": 11,
    "last_accident_date": "2026-08-18",
    "dominant_cause": "High-Speed Traffic Weaving at Rotary Entry",
    "dominant_type": "Side Impact / T-Bone",
    "highest_risk_month": "December",
    "hotspot_score": 86.5,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Road Accidents in India Report",
    "dominant_vehicle": "Two-Wheeler & Light Commercial Vehicle"
  },
  {
    "location_id": "loc-hp-swarghat-descent",
    "road_name": "Chandigarh-Manali Highway",
    "road_number": "NH-205",
    "city": "Bilaspur",
    "locality": "Swarghat Horseshoe Hairpin Descent",
    "latitude": 31.2312,
    "longitude": 76.7123,
    "road_type": "National Highway",
    "state_id": "state-hp",
    "state_name": "Himachal Pradesh",
    "state_code": "HP",
    "district_id": "dist-bilaspur",
    "district_name": "Bilaspur",
    "total_accidents": 7,
    "fatal_accidents": 4,
    "total_deaths": 16,
    "total_injuries": 39,
    "total_critical_injuries": 10,
    "last_accident_date": "2026-07-12",
    "dominant_cause": "Brake Failure on Prolonged Mountain Incline",
    "dominant_type": "Gorge Fall / Overturning",
    "highest_risk_month": "August",
    "hotspot_score": 85,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Official 5,803 Black Spot Audit",
    "dominant_vehicle": "Heavy Freight & Tourist Tempo Traveller"
  },
  {
    "location_id": "loc-uk-teen-dhara",
    "road_name": "Rishikesh-Badrinath All-Weather Road",
    "road_number": "NH-58",
    "city": "Devprayag",
    "locality": "Teen Dhara Landslide & River Gorge Curve",
    "latitude": 30.1345,
    "longitude": 78.5812,
    "road_type": "National Highway",
    "state_id": "state-uk",
    "state_name": "Uttarakhand",
    "state_code": "UK",
    "district_id": "dist-tehri",
    "district_name": "Tehri Garhwal",
    "total_accidents": 6,
    "fatal_accidents": 4,
    "total_deaths": 17,
    "total_injuries": 29,
    "total_critical_injuries": 8,
    "last_accident_date": "2026-08-01",
    "dominant_cause": "Landslide Debris / Wet Mountain Road Skid",
    "dominant_type": "Gorge Plunge / Rockfall",
    "highest_risk_month": "July",
    "hotspot_score": 84,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Road Accidents in India Report",
    "dominant_vehicle": "Pilgrim Bus & Maxi Cab"
  },
  {
    "location_id": "loc-ga-zuari-bridge",
    "road_name": "Panaji-Margao Highway (New Zuari Bridge Approach)",
    "road_number": "NH-66",
    "city": "Agassaim",
    "locality": "Agassaim High-Speed Flyover Merge",
    "latitude": 15.4123,
    "longitude": 73.8745,
    "road_type": "National Highway",
    "state_id": "state-ga",
    "state_name": "Goa",
    "state_code": "GA",
    "district_id": "dist-north-goa",
    "district_name": "North Goa",
    "total_accidents": 6,
    "fatal_accidents": 3,
    "total_deaths": 9,
    "total_injuries": 24,
    "total_critical_injuries": 5,
    "last_accident_date": "2026-07-22",
    "dominant_cause": "Nighttime Overspeeding & Alcohol Impairment",
    "dominant_type": "Barrier Collision / Rollover",
    "highest_risk_month": "December",
    "hotspot_score": 74,
    "hotspot_tier": "High",
    "primary_source": "Goa Traffic Police & MoRTH Audit",
    "dominant_vehicle": "Rental Self-Drive Car & Two-Wheeler"
  },
  {
    "location_id": "loc-jh-koderma-ghat",
    "road_name": "Ranchi-Patna Highway (Koderma Valley Section)",
    "road_number": "NH-20",
    "city": "Koderma",
    "locality": "Meghatari Hairpin Bend Km 84",
    "latitude": 24.5123,
    "longitude": 85.5412,
    "road_type": "National Highway",
    "state_id": "state-jh",
    "state_name": "Jharkhand",
    "state_code": "JH",
    "district_id": "dist-koderma",
    "district_name": "Koderma",
    "total_accidents": 8,
    "fatal_accidents": 5,
    "total_deaths": 18,
    "total_injuries": 42,
    "total_critical_injuries": 11,
    "last_accident_date": "2026-08-11",
    "dominant_cause": "Overloaded Mining Truck Brake Failure",
    "dominant_type": "Head-on Collision & Overturning",
    "highest_risk_month": "September",
    "hotspot_score": 87,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Official 5,803 Black Spot Audit",
    "dominant_vehicle": "Multi-Axle Heavy Coal / Iron Ore Tipper"
  },
  {
    "location_id": "loc-cg-tatibandh-chowk",
    "road_name": "Mumbai-Kolkata Highway (Great Eastern Road)",
    "road_number": "NH-53",
    "city": "Raipur",
    "locality": "Tatibandh Chowk & Transport Nagar Split",
    "latitude": 21.2589,
    "longitude": 81.5678,
    "road_type": "National Highway",
    "state_id": "state-ct",
    "state_name": "Chhattisgarh",
    "state_code": "CG",
    "district_id": "dist-raipur",
    "district_name": "Raipur",
    "total_accidents": 11,
    "fatal_accidents": 6,
    "total_deaths": 20,
    "total_injuries": 51,
    "total_critical_injuries": 14,
    "last_accident_date": "2026-08-25",
    "dominant_cause": "Heavy Freight Mixed With Urban Commuter Traffic",
    "dominant_type": "Hit and Run / Blind Spot Crush",
    "highest_risk_month": "November",
    "hotspot_score": 92,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Road Accidents in India Report",
    "dominant_vehicle": "Heavy Freight Trailer & Two-Wheeler"
  },
  {
    "location_id": "loc-ka-hubballi-bypass",
    "road_name": "Pune-Bengaluru Highway (Hubballi-Dharwad Single Lane Bypass)",
    "road_number": "NH-48",
    "city": "Hubballi",
    "locality": "Km 408 Two-Lane Bottleneck Corridor",
    "latitude": 15.3412,
    "longitude": 75.1212,
    "road_type": "National Highway",
    "state_id": "state-ka",
    "state_name": "Karnataka",
    "state_code": "KA",
    "district_id": "dist-dharwad",
    "district_name": "Dharwad",
    "total_accidents": 12,
    "fatal_accidents": 8,
    "total_deaths": 28,
    "total_injuries": 64,
    "total_critical_injuries": 18,
    "last_accident_date": "2026-08-16",
    "dominant_cause": "Sudden 6-lane to 2-lane Bottleneck Head-on Collision",
    "dominant_type": "Head-on Collision",
    "highest_risk_month": "May",
    "hotspot_score": 97,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Official 5,803 Black Spot Audit",
    "dominant_vehicle": "Multi-Axle Truck & Inter-city Bus"
  },
  {
    "location_id": "loc-dl-kashmere-gate",
    "road_name": "Mahatma Gandhi Ring Road (Kashmere Gate ISBT)",
    "road_number": "Ring Road / NH-44",
    "city": "Delhi",
    "locality": "ISBT Flyover Merge & Pedestrian Crossing",
    "latitude": 28.6675,
    "longitude": 77.2312,
    "road_type": "National Highway",
    "state_id": "state-dl",
    "state_name": "Delhi",
    "state_code": "DL",
    "district_id": "dist-delhi-north",
    "district_name": "North Delhi",
    "total_accidents": 11,
    "fatal_accidents": 6,
    "total_deaths": 17,
    "total_injuries": 46,
    "total_critical_injuries": 12,
    "last_accident_date": "2026-08-20",
    "dominant_cause": "High-Speed Bus-Pedestrian Conflict / Blind Merge",
    "dominant_type": "Pedestrian Hit & Run",
    "highest_risk_month": "November",
    "hotspot_score": 91,
    "hotspot_tier": "Critical",
    "primary_source": "Delhi Traffic Police Annual Crash Analysis",
    "dominant_vehicle": "Interstate Bus & E-Rickshaw"
  },
  {
    "location_id": "loc-dl-signature-bridge",
    "road_name": "Wazirabad Road (Signature Bridge Approach)",
    "road_number": "MDR-DL",
    "city": "Delhi",
    "locality": "Wazirabad Loop Elevated Ramp",
    "latitude": 28.7186,
    "longitude": 77.2341,
    "road_type": "State Highway",
    "state_id": "state-dl",
    "state_name": "Delhi",
    "state_code": "DL",
    "district_id": "dist-delhi-northeast",
    "district_name": "North East Delhi",
    "total_accidents": 8,
    "fatal_accidents": 4,
    "total_deaths": 11,
    "total_injuries": 31,
    "total_critical_injuries": 7,
    "last_accident_date": "2026-07-29",
    "dominant_cause": "High-Speed Curve Skid & Selfie Hazard",
    "dominant_type": "Overturning / Barrier Crash",
    "highest_risk_month": "December",
    "hotspot_score": 82.5,
    "hotspot_tier": "Critical",
    "primary_source": "Delhi Traffic Police Annual Crash Analysis",
    "dominant_vehicle": "Motorcycle & Compact SUV"
  },
  {
    "location_id": "loc-dl-dhaula-kuan",
    "road_name": "Ring Road - Dhaula Kuan Interchange",
    "road_number": "NH-48",
    "city": "Delhi",
    "locality": "NH-48 Grade Separator Underpass",
    "latitude": 28.5912,
    "longitude": 77.1614,
    "road_type": "National Highway",
    "state_id": "state-dl",
    "state_name": "Delhi",
    "state_code": "DL",
    "district_id": "dist-delhi-southwest",
    "district_name": "South West Delhi",
    "total_accidents": 7,
    "fatal_accidents": 3,
    "total_deaths": 9,
    "total_injuries": 28,
    "total_critical_injuries": 5,
    "last_accident_date": "2026-08-11",
    "dominant_cause": "Weaving & Abrupt Lane Change at Divergence",
    "dominant_type": "Side Swipe / Barrier Impact",
    "highest_risk_month": "January",
    "hotspot_score": 79,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH National Capital Region Study",
    "dominant_vehicle": "Cab / Commercial Fleet Car"
  },
  {
    "location_id": "loc-dl-ghazipur-border",
    "road_name": "Delhi-Meerut Expressway / NH-9",
    "road_number": "NH-09",
    "city": "Delhi",
    "locality": "Ghazipur Border Landfill Flyover Curve",
    "latitude": 28.6241,
    "longitude": 77.3298,
    "road_type": "Expressway",
    "state_id": "state-dl",
    "state_name": "Delhi",
    "state_code": "DL",
    "district_id": "dist-delhi-east",
    "district_name": "East Delhi",
    "total_accidents": 9,
    "fatal_accidents": 5,
    "total_deaths": 14,
    "total_injuries": 37,
    "total_critical_injuries": 9,
    "last_accident_date": "2026-08-04",
    "dominant_cause": "Smog Visibility Loss & Heavy Multi-Axle Merge",
    "dominant_type": "Rear-end Pileup",
    "highest_risk_month": "December",
    "hotspot_score": 87.5,
    "hotspot_tier": "Critical",
    "primary_source": "NHAI Expressway Audit",
    "dominant_vehicle": "Heavy Freight Dumper & Two-Wheeler"
  },
  {
    "location_id": "loc-up-purvanchal-km124",
    "road_name": "Purvanchal Expressway",
    "road_number": "P-EXP",
    "city": "Sultanpur",
    "locality": "Km 124 High-Speed Airstrip Zone",
    "latitude": 26.2415,
    "longitude": 82.1124,
    "road_type": "Expressway",
    "state_id": "state-up",
    "state_name": "Uttar Pradesh",
    "state_code": "UP",
    "district_id": "dist-sultanpur",
    "district_name": "Sultanpur",
    "total_accidents": 10,
    "fatal_accidents": 6,
    "total_deaths": 23,
    "total_injuries": 49,
    "total_critical_injuries": 14,
    "last_accident_date": "2026-08-15",
    "dominant_cause": "High-Speed Tyre Delamination & Drowsiness",
    "dominant_type": "Rollover / Median Breach",
    "highest_risk_month": "June",
    "hotspot_score": 93.5,
    "hotspot_tier": "Critical",
    "primary_source": "UPEIDA Safety & Accident Analysis",
    "dominant_vehicle": "Luxury SUV / High-Speed Sedan"
  },
  {
    "location_id": "loc-up-agra-lucknow-fatehabad",
    "road_name": "Agra-Lucknow Expressway",
    "road_number": "AL-EXP",
    "city": "Fatehabad",
    "locality": "Km 65 Fatehabad Toll Loop",
    "latitude": 27.0123,
    "longitude": 78.2981,
    "road_type": "Expressway",
    "state_id": "state-up",
    "state_name": "Uttar Pradesh",
    "state_code": "UP",
    "district_id": "dist-agra",
    "district_name": "Agra",
    "total_accidents": 8,
    "fatal_accidents": 5,
    "total_deaths": 19,
    "total_injuries": 41,
    "total_critical_injuries": 11,
    "last_accident_date": "2026-07-22",
    "dominant_cause": "Highway Hypnosis / Unmanned Vehicle Collision",
    "dominant_type": "Stationary Vehicle Impact",
    "highest_risk_month": "January",
    "hotspot_score": 89.5,
    "hotspot_tier": "Critical",
    "primary_source": "UPEIDA Black Spot Survey",
    "dominant_vehicle": "Sleeper Bus & Container"
  },
  {
    "location_id": "loc-up-nh19-kanpur-fatehpur",
    "road_name": "Grand Trunk Road (NH-19 / Old NH-2)",
    "road_number": "NH-19",
    "city": "Kanpur",
    "locality": "Rania Industrial Bypass Bottleneck",
    "latitude": 26.3982,
    "longitude": 80.0912,
    "road_type": "National Highway",
    "state_id": "state-up",
    "state_name": "Uttar Pradesh",
    "state_code": "UP",
    "district_id": "dist-kanpur-dehat",
    "district_name": "Kanpur Dehat",
    "total_accidents": 13,
    "fatal_accidents": 8,
    "total_deaths": 29,
    "total_injuries": 72,
    "total_critical_injuries": 21,
    "last_accident_date": "2026-08-07",
    "dominant_cause": "Wrong Side Tractor Driving & Heavy Fog",
    "dominant_type": "Head-on Collision",
    "highest_risk_month": "December",
    "hotspot_score": 97,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Verified Black Spot Registry",
    "dominant_vehicle": "Agricultural Trolley & 16-Wheel Truck"
  },
  {
    "location_id": "loc-up-nh24-bareilly-mirganj",
    "road_name": "Delhi-Lucknow Highway (NH-24 / NH-30)",
    "road_number": "NH-30",
    "city": "Bareilly",
    "locality": "Mirganj Sugar Mill Blind Curve",
    "latitude": 28.5412,
    "longitude": 79.1894,
    "road_type": "National Highway",
    "state_id": "state-up",
    "state_name": "Uttar Pradesh",
    "state_code": "UP",
    "district_id": "dist-bareilly",
    "district_name": "Bareilly",
    "total_accidents": 9,
    "fatal_accidents": 5,
    "total_deaths": 18,
    "total_injuries": 45,
    "total_critical_injuries": 12,
    "last_accident_date": "2026-07-14",
    "dominant_cause": "Zero Visibility Winter Fog & Sugar Cane Carts",
    "dominant_type": "Rear-end Collision",
    "highest_risk_month": "January",
    "hotspot_score": 88,
    "hotspot_tier": "Critical",
    "primary_source": "UP State Highway Safety Council",
    "dominant_vehicle": "Sugar Cane Tractor & Tanker"
  },
  {
    "location_id": "loc-up-nh27-gorakhpur",
    "road_name": "East-West Corridor Highway",
    "road_number": "NH-27",
    "city": "Gorakhpur",
    "locality": "Kushinagar Highway Jagdishpur Chauraha",
    "latitude": 26.7312,
    "longitude": 83.4124,
    "road_type": "National Highway",
    "state_id": "state-up",
    "state_name": "Uttar Pradesh",
    "state_code": "UP",
    "district_id": "dist-gorakhpur",
    "district_name": "Gorakhpur",
    "total_accidents": 8,
    "fatal_accidents": 4,
    "total_deaths": 15,
    "total_injuries": 39,
    "total_critical_injuries": 8,
    "last_accident_date": "2026-08-01",
    "dominant_cause": "Unregulated Median Openings & High-Speed Transit",
    "dominant_type": "T-Bone Intersection Crash",
    "highest_risk_month": "August",
    "hotspot_score": 84,
    "hotspot_tier": "Critical",
    "primary_source": "NHAI Project Implementation Unit (PIU)",
    "dominant_vehicle": "Commercial LCV & Two-Wheeler"
  },
  {
    "location_id": "loc-mh-samruddhi-buldhana",
    "road_name": "Samruddhi Mahamarg (Mumbai-Nagpur Expressway)",
    "road_number": "MS-EXP-01",
    "city": "Sindkhed Raja",
    "locality": "Km 295 Pimpalkhuta Overpass (Sleeper Bus Crash Zone)",
    "latitude": 20.0841,
    "longitude": 76.1287,
    "road_type": "Expressway",
    "state_id": "state-mh",
    "state_name": "Maharashtra",
    "state_code": "MH",
    "district_id": "dist-buldhana",
    "district_name": "Buldhana",
    "total_accidents": 12,
    "fatal_accidents": 8,
    "total_deaths": 36,
    "total_injuries": 68,
    "total_critical_injuries": 22,
    "last_accident_date": "2026-08-18",
    "dominant_cause": "Highway Hypnosis / Tyre Burst & Pole Impact",
    "dominant_type": "Post-Collision Fire & Rollover",
    "highest_risk_month": "July",
    "hotspot_score": 99,
    "hotspot_tier": "Critical",
    "primary_source": "Maharashtra Highway Safety Patrol (HSP)",
    "dominant_vehicle": "Multi-Axle Sleeper AC Coach"
  },
  {
    "location_id": "loc-mh-samruddhi-washim",
    "road_name": "Samruddhi Mahamarg (Mumbai-Nagpur Expressway)",
    "road_number": "MS-EXP-01",
    "city": "Karanja",
    "locality": "Km 340 Lad Interchange Straight Stretch",
    "latitude": 20.4812,
    "longitude": 77.4912,
    "road_type": "Expressway",
    "state_id": "state-mh",
    "state_name": "Maharashtra",
    "state_code": "MH",
    "district_id": "dist-washim",
    "district_name": "Washim",
    "total_accidents": 7,
    "fatal_accidents": 4,
    "total_deaths": 16,
    "total_injuries": 34,
    "total_critical_injuries": 9,
    "last_accident_date": "2026-07-26",
    "dominant_cause": "Monotonous Driving Fatigue / Excessive Speed",
    "dominant_type": "Rear Collision with Heavy Freight",
    "highest_risk_month": "May",
    "hotspot_score": 86.5,
    "hotspot_tier": "Critical",
    "primary_source": "MSRDC Road Safety Audit",
    "dominant_vehicle": "Private Sedan & Fuel Tanker"
  },
  {
    "location_id": "loc-mh-kasara-ghat",
    "road_name": "Mumbai-Nashik Highway (Thal Ghat Section)",
    "road_number": "NH-160",
    "city": "Igatpuri",
    "locality": "Kasara Ghat Hairpin Curve Descent",
    "latitude": 19.6894,
    "longitude": 73.4912,
    "road_type": "National Highway",
    "state_id": "state-mh",
    "state_name": "Maharashtra",
    "state_code": "MH",
    "district_id": "dist-thane",
    "district_name": "Thane",
    "total_accidents": 11,
    "fatal_accidents": 6,
    "total_deaths": 24,
    "total_injuries": 57,
    "total_critical_injuries": 16,
    "last_accident_date": "2026-08-09",
    "dominant_cause": "Heavy Monsoon Brake Failure & Rock Fall",
    "dominant_type": "Valley Fall / Overturning",
    "highest_risk_month": "August",
    "hotspot_score": 94,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH - Official 5,803 Black Spot Audit",
    "dominant_vehicle": "Heavy Freight Container & ST Bus"
  },
  {
    "location_id": "loc-mh-kolhapur-kagal",
    "road_name": "Pune-Bengaluru Highway",
    "road_number": "NH-48",
    "city": "Kolhapur",
    "locality": "Kagal Five Star MIDC Intersection",
    "latitude": 16.5784,
    "longitude": 74.3124,
    "road_type": "National Highway",
    "state_id": "state-mh",
    "state_name": "Maharashtra",
    "state_code": "MH",
    "district_id": "dist-kolhapur",
    "district_name": "Kolhapur",
    "total_accidents": 8,
    "fatal_accidents": 4,
    "total_deaths": 14,
    "total_injuries": 38,
    "total_critical_injuries": 8,
    "last_accident_date": "2026-08-03",
    "dominant_cause": "Industrial Traffic Merge & Sudden Braking",
    "dominant_type": "Rear-end & Broadside",
    "highest_risk_month": "February",
    "hotspot_score": 83.5,
    "hotspot_tier": "Critical",
    "primary_source": "Kolhapur District Road Safety Committee",
    "dominant_vehicle": "Multi-Axle Truck & Two-Wheeler"
  },
  {
    "location_id": "loc-tn-madurai-virudhunagar",
    "road_name": "Madurai-Kanyakumari Highway",
    "road_number": "NH-44",
    "city": "Virudhunagar",
    "locality": "Kalligudi Toll Plaza S-Bend",
    "latitude": 9.7412,
    "longitude": 77.9621,
    "road_type": "National Highway",
    "state_id": "state-tn",
    "state_name": "Tamil Nadu",
    "state_code": "TN",
    "district_id": "dist-virudhunagar",
    "district_name": "Virudhunagar",
    "total_accidents": 10,
    "fatal_accidents": 6,
    "total_deaths": 22,
    "total_injuries": 51,
    "total_critical_injuries": 13,
    "last_accident_date": "2026-08-12",
    "dominant_cause": "Night Vision Glare & High Speed Transit",
    "dominant_type": "Head-on Median Impact",
    "highest_risk_month": "January",
    "hotspot_score": 92.5,
    "hotspot_tier": "Critical",
    "primary_source": "Tamil Nadu Police Road Safety Wing",
    "dominant_vehicle": "Omni Sleeper Bus & Lorry"
  },
  {
    "location_id": "loc-tn-salem-avinashi",
    "road_name": "Salem-Kochi Highway",
    "road_number": "NH-544",
    "city": "Tiruppur",
    "locality": "Avinashi Bypass Near Bridge Km 44",
    "latitude": 11.1924,
    "longitude": 77.2684,
    "road_type": "National Highway",
    "state_id": "state-tn",
    "state_name": "Tamil Nadu",
    "state_code": "TN",
    "district_id": "dist-tiruppur",
    "district_name": "Tiruppur",
    "total_accidents": 11,
    "fatal_accidents": 7,
    "total_deaths": 26,
    "total_injuries": 63,
    "total_critical_injuries": 17,
    "last_accident_date": "2026-08-05",
    "dominant_cause": "Container Truck Tyre Burst & Opposite Lane Breach",
    "dominant_type": "Cross-Median Catastrophic Crash",
    "highest_risk_month": "February",
    "hotspot_score": 96,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH 5,803 Black Spot Audit",
    "dominant_vehicle": "Inter-State Container & KSRTC Bus"
  },
  {
    "location_id": "loc-tn-ecr-mahabalipuram",
    "road_name": "East Coast Road Scenic Expressway",
    "road_number": "SH-49",
    "city": "Mahabalipuram",
    "locality": "Kovalam-Nemmeli S-Curve Coastal Sector",
    "latitude": 12.7124,
    "longitude": 80.2412,
    "road_type": "State Highway",
    "state_id": "state-tn",
    "state_name": "Tamil Nadu",
    "state_code": "TN",
    "district_id": "dist-chengalpattu",
    "district_name": "Chengalpattu",
    "total_accidents": 8,
    "fatal_accidents": 4,
    "total_deaths": 15,
    "total_injuries": 36,
    "total_critical_injuries": 9,
    "last_accident_date": "2026-07-25",
    "dominant_cause": "Joyriding Overspeeding on Sharp Seaward Curve",
    "dominant_type": "Tree Impact / Skidding",
    "highest_risk_month": "December",
    "hotspot_score": 84.5,
    "hotspot_tier": "Critical",
    "primary_source": "Tamil Nadu Highways Department (TNRDC)",
    "dominant_vehicle": "Superbike & High-End Hatchback"
  },
  {
    "location_id": "loc-tn-ulundurpet-nh38",
    "road_name": "Chennai-Tiruchirappalli Highway",
    "road_number": "NH-38",
    "city": "Ulundurpet",
    "locality": "Salem Bypass Tri-Junction Toll",
    "latitude": 11.6912,
    "longitude": 79.2941,
    "road_type": "National Highway",
    "state_id": "state-tn",
    "state_name": "Tamil Nadu",
    "state_code": "TN",
    "district_id": "dist-kallakurichi",
    "district_name": "Kallakurichi",
    "total_accidents": 9,
    "fatal_accidents": 5,
    "total_deaths": 20,
    "total_injuries": 48,
    "total_critical_injuries": 14,
    "last_accident_date": "2026-08-08",
    "dominant_cause": "High-Speed Convergence at Toll Plaza Approach",
    "dominant_type": "Rear-end & Barrier Impact",
    "highest_risk_month": "May",
    "hotspot_score": 90,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH Official Audit",
    "dominant_vehicle": "SETC Government Bus & Goods Carrier"
  },
  {
    "location_id": "loc-ka-mysuru-exp-bidadi",
    "road_name": "Bengaluru-Mysuru Access-Controlled Expressway",
    "road_number": "NH-275",
    "city": "Bidadi",
    "locality": "Byramangala Overpass Curve Km 31",
    "latitude": 12.7912,
    "longitude": 77.3821,
    "road_type": "Expressway",
    "state_id": "state-ka",
    "state_name": "Karnataka",
    "state_code": "KA",
    "district_id": "dist-ramanagara",
    "district_name": "Ramanagara",
    "total_accidents": 10,
    "fatal_accidents": 6,
    "total_deaths": 22,
    "total_injuries": 54,
    "total_critical_injuries": 15,
    "last_accident_date": "2026-08-17",
    "dominant_cause": "High-Speed Rear Collision on Rainy Gradient",
    "dominant_type": "Aquaplaning & Barrier Crash",
    "highest_risk_month": "July",
    "hotspot_score": 93,
    "hotspot_tier": "Critical",
    "primary_source": "NHAI Karnataka Regional Office",
    "dominant_vehicle": "Private Car & Intercity KSRTC Bus"
  },
  {
    "location_id": "loc-ka-tumakuru-sira",
    "road_name": "Pune-Bengaluru Highway (Tumakuru-Sira section)",
    "road_number": "NH-48",
    "city": "Sira",
    "locality": "Tavarekere Curve Km 112",
    "latitude": 13.7412,
    "longitude": 76.9012,
    "road_type": "National Highway",
    "state_id": "state-ka",
    "state_name": "Karnataka",
    "state_code": "KA",
    "district_id": "dist-tumakuru",
    "district_name": "Tumakuru",
    "total_accidents": 9,
    "fatal_accidents": 5,
    "total_deaths": 20,
    "total_injuries": 49,
    "total_critical_injuries": 13,
    "last_accident_date": "2026-08-06",
    "dominant_cause": "Heavy Truck Stationary Breakdowns on Shoulder",
    "dominant_type": "Rear-end Underride Crash",
    "highest_risk_month": "March",
    "hotspot_score": 90.5,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH Official 5,803 Black Spot Audit",
    "dominant_vehicle": "Stationary Freight Lorry & SUV"
  },
  {
    "location_id": "loc-ka-nelamangala-toll",
    "road_name": "Bengaluru Elevated Tollway Merge",
    "road_number": "NH-48",
    "city": "Nelamangala",
    "locality": "Jasmin Toll Plaza Bottleneck",
    "latitude": 13.0984,
    "longitude": 77.3912,
    "road_type": "National Highway",
    "state_id": "state-ka",
    "state_name": "Karnataka",
    "state_code": "KA",
    "district_id": "dist-bengaluru-rural",
    "district_name": "Bengaluru Rural",
    "total_accidents": 7,
    "fatal_accidents": 3,
    "total_deaths": 11,
    "total_injuries": 33,
    "total_critical_injuries": 8,
    "last_accident_date": "2026-07-20",
    "dominant_cause": "High Congestion Stop-and-Go Rear Collisions",
    "dominant_type": "Multi-Vehicle Chain Impact",
    "highest_risk_month": "October",
    "hotspot_score": 80,
    "hotspot_tier": "Critical",
    "primary_source": "Bengaluru City Police Traffic Wing",
    "dominant_vehicle": "Maxicab & Intercity Bus"
  },
  {
    "location_id": "loc-kl-wayanad-churam",
    "road_name": "Kozhikode-Kollegal Highway (Thamarassery Churam)",
    "road_number": "NH-766",
    "city": "Adivaram",
    "locality": "Hairpin Bend 9 (Lakkidi Gap Descent)",
    "latitude": 11.5124,
    "longitude": 76.0241,
    "road_type": "National Highway",
    "state_id": "state-kl",
    "state_name": "Kerala",
    "state_code": "KL",
    "district_id": "dist-kozhikode",
    "district_name": "Kozhikode",
    "total_accidents": 10,
    "fatal_accidents": 5,
    "total_deaths": 19,
    "total_injuries": 55,
    "total_critical_injuries": 14,
    "last_accident_date": "2026-08-10",
    "dominant_cause": "Brake Loss on Heavy Incline & Gorge Plummet",
    "dominant_type": "Gorge Descent Overturning",
    "highest_risk_month": "August",
    "hotspot_score": 91.5,
    "hotspot_tier": "Critical",
    "primary_source": "Kerala Road Safety Authority (KRSA)",
    "dominant_vehicle": "Tourist Van & Timber Lorry"
  },
  {
    "location_id": "loc-kl-mc-road-chengannur",
    "road_name": "Main Central Road (MC Road)",
    "road_number": "SH-01",
    "city": "Chengannur",
    "locality": "Enathu Bridge Approach Blind Curve",
    "latitude": 9.3124,
    "longitude": 76.6184,
    "road_type": "State Highway",
    "state_id": "state-kl",
    "state_name": "Kerala",
    "state_code": "KL",
    "district_id": "dist-alappuzha",
    "district_name": "Alappuzha",
    "total_accidents": 8,
    "fatal_accidents": 4,
    "total_deaths": 13,
    "total_injuries": 37,
    "total_critical_injuries": 9,
    "last_accident_date": "2026-07-16",
    "dominant_cause": "Narrow High-Speed Curve & River Bank Hazard",
    "dominant_type": "Head-on Collision",
    "highest_risk_month": "January",
    "hotspot_score": 82,
    "hotspot_tier": "Critical",
    "primary_source": "Kerala Police NATPAC Survey",
    "dominant_vehicle": "KSRTC Fast Passenger & Two-Wheeler"
  },
  {
    "location_id": "loc-kl-walayar-palakkad",
    "road_name": "Salem-Kochi Corridor Highway",
    "road_number": "NH-544",
    "city": "Palakkad",
    "locality": "Kanjikode Industrial Bypass Stretch",
    "latitude": 10.7912,
    "longitude": 76.7412,
    "road_type": "National Highway",
    "state_id": "state-kl",
    "state_name": "Kerala",
    "state_code": "KL",
    "district_id": "dist-palakkad",
    "district_name": "Palakkad",
    "total_accidents": 7,
    "fatal_accidents": 4,
    "total_deaths": 14,
    "total_injuries": 32,
    "total_critical_injuries": 8,
    "last_accident_date": "2026-08-02",
    "dominant_cause": "Early Morning Drowsiness & Pedestrian Conflict",
    "dominant_type": "Hit & Run / Underride",
    "highest_risk_month": "April",
    "hotspot_score": 81.5,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH National Highway Division",
    "dominant_vehicle": "Heavy Trailer & Pedestrian"
  },
  {
    "location_id": "loc-rj-delhi-jaipur-shahpura",
    "road_name": "Delhi-Jaipur National Highway",
    "road_number": "NH-48",
    "city": "Shahpura",
    "locality": "Manoharpur-Shahpura Flyover Merge",
    "latitude": 27.3891,
    "longitude": 75.9621,
    "road_type": "National Highway",
    "state_id": "state-rj",
    "state_name": "Rajasthan",
    "state_code": "RJ",
    "district_id": "dist-jaipur",
    "district_name": "Jaipur",
    "total_accidents": 12,
    "fatal_accidents": 7,
    "total_deaths": 27,
    "total_injuries": 61,
    "total_critical_injuries": 16,
    "last_accident_date": "2026-08-13",
    "dominant_cause": "High-Speed Night Racing & Unlit Camel Carts",
    "dominant_type": "Rear-end High-Impact Collision",
    "highest_risk_month": "November",
    "hotspot_score": 95.5,
    "hotspot_tier": "Critical",
    "primary_source": "Rajasthan Police Road Safety Cell",
    "dominant_vehicle": "Interstate Sleeper Bus & Heavy Truck"
  },
  {
    "location_id": "loc-rj-dausa-lalsot",
    "road_name": "Agra-Jaipur Highway / Delhi-Mumbai Exp Link",
    "road_number": "NH-21",
    "city": "Dausa",
    "locality": "Bhandarej Mor Intersection",
    "latitude": 26.8912,
    "longitude": 76.3341,
    "road_type": "National Highway",
    "state_id": "state-rj",
    "state_name": "Rajasthan",
    "state_code": "RJ",
    "district_id": "dist-dausa",
    "district_name": "Dausa",
    "total_accidents": 9,
    "fatal_accidents": 5,
    "total_deaths": 18,
    "total_injuries": 43,
    "total_critical_injuries": 11,
    "last_accident_date": "2026-07-27",
    "dominant_cause": "Expressway Ramp Convergence at 120 km/h",
    "dominant_type": "Broadside Collision",
    "highest_risk_month": "May",
    "hotspot_score": 88.5,
    "hotspot_tier": "Critical",
    "primary_source": "NHAI Rajasthan RO",
    "dominant_vehicle": "Fast Sedan & Tractor Trolley"
  },
  {
    "location_id": "loc-rj-udaipur-pindwara",
    "road_name": "East-West Corridor (Udaipur-Pindwara Highway)",
    "road_number": "NH-27",
    "city": "Pindwara",
    "locality": "Gogunda Tunnel Pass Section",
    "latitude": 24.7612,
    "longitude": 73.5124,
    "road_type": "National Highway",
    "state_id": "state-rj",
    "state_name": "Rajasthan",
    "state_code": "RJ",
    "district_id": "dist-udaipur",
    "district_name": "Udaipur",
    "total_accidents": 8,
    "fatal_accidents": 5,
    "total_deaths": 19,
    "total_injuries": 40,
    "total_critical_injuries": 12,
    "last_accident_date": "2026-08-04",
    "dominant_cause": "Heavy Truck Brake Failure on Aravalli Incline",
    "dominant_type": "Multi-Vehicle Pileup",
    "highest_risk_month": "August",
    "hotspot_score": 89.5,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH Verified Black Spot Audit",
    "dominant_vehicle": "Marble Freight Truck & Passenger Jeep"
  },
  {
    "location_id": "loc-rj-chambal-kota",
    "road_name": "Kota Bypass Highway",
    "road_number": "NH-27",
    "city": "Kota",
    "locality": "Chambal Cable Stayed Bridge Approach",
    "latitude": 25.1384,
    "longitude": 75.7912,
    "road_type": "National Highway",
    "state_id": "state-rj",
    "state_name": "Rajasthan",
    "state_code": "RJ",
    "district_id": "dist-kota",
    "district_name": "Kota",
    "total_accidents": 7,
    "fatal_accidents": 3,
    "total_deaths": 12,
    "total_injuries": 31,
    "total_critical_injuries": 7,
    "last_accident_date": "2026-07-18",
    "dominant_cause": "High Crosswinds & Speeding on Elevated Deck",
    "dominant_type": "Barrier Impact / Overturning",
    "highest_risk_month": "June",
    "hotspot_score": 79.5,
    "hotspot_tier": "Critical",
    "primary_source": "Rajasthan PWD Safety Audit",
    "dominant_vehicle": "Multi-Axle Freight & Two-Wheeler"
  },
  {
    "location_id": "loc-gj-bharuch-narmada",
    "road_name": "Delhi-Mumbai Highway (Narmada River Crossing)",
    "road_number": "NH-48",
    "city": "Bharuch",
    "locality": "Narmada Cable Bridge North Approach",
    "latitude": 21.7124,
    "longitude": 73.0124,
    "road_type": "National Highway",
    "state_id": "state-gj",
    "state_name": "Gujarat",
    "state_code": "GJ",
    "district_id": "dist-bharuch",
    "district_name": "Bharuch",
    "total_accidents": 10,
    "fatal_accidents": 6,
    "total_deaths": 23,
    "total_injuries": 53,
    "total_critical_injuries": 15,
    "last_accident_date": "2026-08-11",
    "dominant_cause": "Heavy Chemical Tanker Breakdown & Rear Impact",
    "dominant_type": "Rear-end Underride & Hazard Leak",
    "highest_risk_month": "March",
    "hotspot_score": 93,
    "hotspot_tier": "Critical",
    "primary_source": "Gujarat Police Traffic Branch",
    "dominant_vehicle": "Chemical Tanker & Luxury Bus"
  },
  {
    "location_id": "loc-gj-ahmedabad-vadodara",
    "road_name": "Mahatma Gandhi National Expressway 1",
    "road_number": "NE-01",
    "city": "Anand",
    "locality": "Km 45 Nadiad-Anand Interchange Curve",
    "latitude": 22.6841,
    "longitude": 72.8712,
    "road_type": "Expressway",
    "state_id": "state-gj",
    "state_name": "Gujarat",
    "state_code": "GJ",
    "district_id": "dist-anand",
    "district_name": "Anand",
    "total_accidents": 9,
    "fatal_accidents": 5,
    "total_deaths": 18,
    "total_injuries": 44,
    "total_critical_injuries": 11,
    "last_accident_date": "2026-07-29",
    "dominant_cause": "Over-speeding Above 120 km/h & Tailgating",
    "dominant_type": "High-Speed Rear Crash",
    "highest_risk_month": "January",
    "hotspot_score": 89,
    "hotspot_tier": "Critical",
    "primary_source": "NHAI Ahmedabad Expressway PIU",
    "dominant_vehicle": "Commercial Taxi & Private Sedan"
  },
  {
    "location_id": "loc-gj-rajkot-morbi",
    "road_name": "Rajkot-Morbi Ceramic Highway",
    "road_number": "SH-24",
    "city": "Morbi",
    "locality": "Lajai Ceramic Zone Intersection",
    "latitude": 22.7612,
    "longitude": 70.8412,
    "road_type": "State Highway",
    "state_id": "state-gj",
    "state_name": "Gujarat",
    "state_code": "GJ",
    "district_id": "dist-morbi",
    "district_name": "Morbi",
    "total_accidents": 8,
    "fatal_accidents": 4,
    "total_deaths": 15,
    "total_injuries": 39,
    "total_critical_injuries": 10,
    "last_accident_date": "2026-08-07",
    "dominant_cause": "Heavy Dust Blindness & Overloaded Ceramic Trucks",
    "dominant_type": "Head-on Collision",
    "highest_risk_month": "February",
    "hotspot_score": 84.5,
    "hotspot_tier": "Critical",
    "primary_source": "Gujarat State Safety Council",
    "dominant_vehicle": "Heavy Ceramic Dumper & Auto-Rickshaw"
  },
  {
    "location_id": "loc-ap-vijayawada-guntur",
    "road_name": "Chennai-Kolkata Golden Quadrilateral",
    "road_number": "NH-16",
    "city": "Mangalagiri",
    "locality": "AIIMS Mangalagiri Junction Underpass",
    "latitude": 16.4384,
    "longitude": 80.5712,
    "road_type": "National Highway",
    "state_id": "state-ap",
    "state_name": "Andhra Pradesh",
    "state_code": "AP",
    "district_id": "dist-guntur",
    "district_name": "Guntur",
    "total_accidents": 11,
    "fatal_accidents": 7,
    "total_deaths": 26,
    "total_injuries": 59,
    "total_critical_injuries": 16,
    "last_accident_date": "2026-08-16",
    "dominant_cause": "High-Speed U-Turn Cut & Highway Speeding",
    "dominant_type": "Broadside T-Bone Crash",
    "highest_risk_month": "April",
    "hotspot_score": 95,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH Official 5,803 Black Spot Audit",
    "dominant_vehicle": "APSRTC Bus & Agricultural Tractor"
  },
  {
    "location_id": "loc-ap-anandapuram-vizag",
    "road_name": "Visakhapatnam Bypass Corridor",
    "road_number": "NH-16",
    "city": "Visakhapatnam",
    "locality": "Anandapuram Junction Flyover Descent",
    "latitude": 17.8912,
    "longitude": 83.3912,
    "road_type": "National Highway",
    "state_id": "state-ap",
    "state_name": "Andhra Pradesh",
    "state_code": "AP",
    "district_id": "dist-visakhapatnam",
    "district_name": "Visakhapatnam",
    "total_accidents": 8,
    "fatal_accidents": 5,
    "total_deaths": 18,
    "total_injuries": 41,
    "total_critical_injuries": 11,
    "last_accident_date": "2026-07-24",
    "dominant_cause": "Heavy Monsoon Aquaplaning & High Speed",
    "dominant_type": "Skid / Median Breach",
    "highest_risk_month": "October",
    "hotspot_score": 88,
    "hotspot_tier": "Critical",
    "primary_source": "Andhra Pradesh Police Transport Wing",
    "dominant_vehicle": "Lorry & Intercity Tourist Van"
  },
  {
    "location_id": "loc-ts-orr-shamshabad",
    "road_name": "Nehru Outer Ring Road (Hyderabad ORR)",
    "road_number": "ORR-TS",
    "city": "Hyderabad",
    "locality": "Exit 16 Shamshabad Airport Interchange",
    "latitude": 17.2412,
    "longitude": 78.4312,
    "road_type": "Expressway",
    "state_id": "state-ts",
    "state_name": "Telangana",
    "state_code": "TS",
    "district_id": "dist-rangareddy",
    "district_name": "Ranga Reddy",
    "total_accidents": 9,
    "fatal_accidents": 5,
    "total_deaths": 21,
    "total_injuries": 46,
    "total_critical_injuries": 13,
    "last_accident_date": "2026-08-14",
    "dominant_cause": "Tyre Blowout at 120 km/h & Midnight Sleepiness",
    "dominant_type": "High-Impact Guardrail Rollover",
    "highest_risk_month": "December",
    "hotspot_score": 91,
    "hotspot_tier": "Critical",
    "primary_source": "Cyberabad Police Traffic Wing",
    "dominant_vehicle": "Airport Cab & Luxury SUV"
  },
  {
    "location_id": "loc-ts-rajiv-rahadari",
    "road_name": "State Highway 1 (Rajiv Rahadari)",
    "road_number": "SH-01",
    "city": "Gajwel",
    "locality": "Pragnapur Intersection Bypass",
    "latitude": 17.8412,
    "longitude": 78.6912,
    "road_type": "State Highway",
    "state_id": "state-ts",
    "state_name": "Telangana",
    "state_code": "TS",
    "district_id": "dist-siddipet",
    "district_name": "Siddipet",
    "total_accidents": 8,
    "fatal_accidents": 4,
    "total_deaths": 16,
    "total_injuries": 37,
    "total_critical_injuries": 9,
    "last_accident_date": "2026-07-21",
    "dominant_cause": "High-Speed Commercial Transit & Rural Crossing",
    "dominant_type": "Head-on Collision",
    "highest_risk_month": "May",
    "hotspot_score": 85,
    "hotspot_tier": "Critical",
    "primary_source": "Telangana Road Safety Authority",
    "dominant_vehicle": "TSRTC Express Bus & Tipper Truck"
  },
  {
    "location_id": "loc-wb-dankuni-nh19",
    "road_name": "Durgapur Expressway",
    "road_number": "NH-19",
    "city": "Dankuni",
    "locality": "Dankuni Toll Plaza 8-Lane Merge",
    "latitude": 22.6841,
    "longitude": 88.2912,
    "road_type": "National Highway",
    "state_id": "state-wb",
    "state_name": "West Bengal",
    "state_code": "WB",
    "district_id": "dist-hooghly",
    "district_name": "Hooghly",
    "total_accidents": 11,
    "fatal_accidents": 7,
    "total_deaths": 25,
    "total_injuries": 60,
    "total_critical_injuries": 16,
    "last_accident_date": "2026-08-09",
    "dominant_cause": "Dense Winter Fog & Blind Toll Merge",
    "dominant_type": "Multi-Truck Chain Collision",
    "highest_risk_month": "December",
    "hotspot_score": 95,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH Eastern Region Safety Audit",
    "dominant_vehicle": "Coal Freight Truck & Matador"
  },
  {
    "location_id": "loc-od-rasulgarh-cuttack",
    "road_name": "Cuttack-Bhubaneswar Expressway",
    "road_number": "NH-16",
    "city": "Bhubaneswar",
    "locality": "Rasulgarh Square Flyover Merge",
    "latitude": 20.2984,
    "longitude": 85.8612,
    "road_type": "National Highway",
    "state_id": "state-od",
    "state_name": "Odisha",
    "state_code": "OD",
    "district_id": "dist-khordha",
    "district_name": "Khordha",
    "total_accidents": 10,
    "fatal_accidents": 6,
    "total_deaths": 21,
    "total_injuries": 52,
    "total_critical_injuries": 14,
    "last_accident_date": "2026-08-04",
    "dominant_cause": "Overspeeding on Elevated Flyover Ramp",
    "dominant_type": "Hit & Run Pedestrian / Rear-end",
    "highest_risk_month": "November",
    "hotspot_score": 91.5,
    "hotspot_tier": "Critical",
    "primary_source": "Odisha State Road Safety Society (OSRSS)",
    "dominant_vehicle": "Iron Ore Dumper & Motorcycle"
  },
  {
    "location_id": "loc-od-chandikhole",
    "road_name": "Mining Corridor Junction (NH-16 & NH-53)",
    "road_number": "NH-16",
    "city": "Chandikhole",
    "locality": "Paradeep Port Heavy Truck Divergence",
    "latitude": 20.7124,
    "longitude": 86.1412,
    "road_type": "National Highway",
    "state_id": "state-od",
    "state_name": "Odisha",
    "state_code": "OD",
    "district_id": "dist-jajpur",
    "district_name": "Jajpur",
    "total_accidents": 9,
    "fatal_accidents": 5,
    "total_deaths": 20,
    "total_injuries": 45,
    "total_critical_injuries": 13,
    "last_accident_date": "2026-07-28",
    "dominant_cause": "Overloaded Ore Trucks & Driver Exhaustion",
    "dominant_type": "Head-on / Underride",
    "highest_risk_month": "June",
    "hotspot_score": 90,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH Verified 5,803 Black Spot Audit",
    "dominant_vehicle": "Multi-Axle Mineral Tipper & Bus"
  },
  {
    "location_id": "loc-hr-panipat-elevated",
    "road_name": "Grand Trunk Road (Panipat Elevated Highway)",
    "road_number": "NH-44",
    "city": "Panipat",
    "locality": "Tollway Northern Descent Curve",
    "latitude": 29.3912,
    "longitude": 76.9712,
    "road_type": "National Highway",
    "state_id": "state-hr",
    "state_name": "Haryana",
    "state_code": "HR",
    "district_id": "dist-panipat",
    "district_name": "Panipat",
    "total_accidents": 10,
    "fatal_accidents": 6,
    "total_deaths": 24,
    "total_injuries": 56,
    "total_critical_injuries": 15,
    "last_accident_date": "2026-08-12",
    "dominant_cause": "Dense Winter Fog & Blind Descent Speed",
    "dominant_type": "Multi-Vehicle Pileup",
    "highest_risk_month": "January",
    "hotspot_score": 94,
    "hotspot_tier": "Critical",
    "primary_source": "Haryana Police Highway Patrol",
    "dominant_vehicle": "Heavy Freight Lorry & SUV"
  },
  {
    "location_id": "loc-hr-murthal-nh44",
    "road_name": "Delhi-Chandigarh Highway",
    "road_number": "NH-44",
    "city": "Sonipat",
    "locality": "Murthal Dhabas High Speed Corridor",
    "latitude": 29.0241,
    "longitude": 77.0712,
    "road_type": "National Highway",
    "state_id": "state-hr",
    "state_name": "Haryana",
    "state_code": "HR",
    "district_id": "dist-sonipat",
    "district_name": "Sonipat",
    "total_accidents": 12,
    "fatal_accidents": 7,
    "total_deaths": 28,
    "total_injuries": 64,
    "total_critical_injuries": 18,
    "last_accident_date": "2026-08-17",
    "dominant_cause": "Drunken Driving / Late Night Speeding at 140 km/h",
    "dominant_type": "Rollover & High-Speed Median Crash",
    "highest_risk_month": "December",
    "hotspot_score": 97.5,
    "hotspot_tier": "Critical",
    "primary_source": "MoRTH Official 5,803 Black Spot Audit",
    "dominant_vehicle": "Luxury Sedan & Superbike"
  },
  {
    "location_id": "loc-hr-trans-haryana-152d",
    "road_name": "Trans-Haryana Expressway",
    "road_number": "NH-152D",
    "city": "Mahendragarh",
    "locality": "Km 182 Narnaul Section Straightaway",
    "latitude": 28.2912,
    "longitude": 76.1412,
    "road_type": "Expressway",
    "state_id": "state-hr",
    "state_name": "Haryana",
    "state_code": "HR",
    "district_id": "dist-mahendragarh",
    "district_name": "Mahendragarh",
    "total_accidents": 8,
    "fatal_accidents": 5,
    "total_deaths": 19,
    "total_injuries": 38,
    "total_critical_injuries": 10,
    "last_accident_date": "2026-07-25",
    "dominant_cause": "Driver Sleep Deprivation & Road Hypnosis",
    "dominant_type": "Underride Rear Crash",
    "highest_risk_month": "June",
    "hotspot_score": 89,
    "hotspot_tier": "Critical",
    "primary_source": "NHAI Trans-Haryana Safety Wing",
    "dominant_vehicle": "Container Truck & Car"
  },
  {
    "location_id": "loc-pb-ludhiana-sherpur",
    "road_name": "Delhi-Amritsar Highway (Sherpur Chowk)",
    "road_number": "NH-44",
    "city": "Ludhiana",
    "locality": "Sherpur Chowk Elevated Flyover Bottleneck",
    "latitude": 30.8912,
    "longitude": 75.8912,
    "road_type": "National Highway",
    "state_id": "state-pb",
    "state_name": "Punjab",
    "state_code": "PB",
    "district_id": "dist-ludhiana",
    "district_name": "Ludhiana",
    "total_accidents": 9,
    "fatal_accidents": 5,
    "total_deaths": 20,
    "total_injuries": 47,
    "total_critical_injuries": 12,
    "last_accident_date": "2026-08-01",
    "dominant_cause": "Industrial Freight Convergence & Fog",
    "dominant_type": "Side Swipe / Pileup",
    "highest_risk_month": "January",
    "hotspot_score": 90,
    "hotspot_tier": "Critical",
    "primary_source": "Punjab Police Traffic & Road Safety Wing",
    "dominant_vehicle": "Multi-Axle Trailer & Tractor"
  },
  {
    "location_id": "loc-jk-ramban-nh44",
    "road_name": "Jammu-Srinagar Highway (Panthyal-Ramban Sector)",
    "road_number": "NH-44",
    "city": "Ramban",
    "locality": "Panthyal Shooting Stones Zone (Km 142)",
    "latitude": 33.2412,
    "longitude": 75.2412,
    "road_type": "National Highway",
    "state_id": "state-jk",
    "state_name": "Jammu & Kashmir",
    "state_code": "JK",
    "district_id": "dist-ramban",
    "district_name": "Ramban",
    "total_accidents": 11,
    "fatal_accidents": 7,
    "total_deaths": 31,
    "total_injuries": 68,
    "total_critical_injuries": 19,
    "last_accident_date": "2026-08-16",
    "dominant_cause": "Shooting Stones & Sudden Deep Valley Plunge",
    "dominant_type": "Gorge Descent / Rock Impact",
    "highest_risk_month": "March",
    "hotspot_score": 98,
    "hotspot_tier": "Critical",
    "primary_source": "J&K Traffic Police Highway Control Room",
    "dominant_vehicle": "Passenger Tavera / Sumo & Oil Tanker"
  },
  {
    "location_id": "loc-as-kaziranga-nh27",
    "road_name": "Assam East-West Corridor (Kaziranga Stretch)",
    "road_number": "NH-27",
    "city": "Bokakhat",
    "locality": "Panbari Animal Corridor Animal Crossing",
    "latitude": 26.5912,
    "longitude": 93.3812,
    "road_type": "National Highway",
    "state_id": "state-as",
    "state_name": "Assam",
    "state_code": "AS",
    "district_id": "dist-golaghat",
    "district_name": "Golaghat",
    "total_accidents": 8,
    "fatal_accidents": 4,
    "total_deaths": 14,
    "total_injuries": 36,
    "total_critical_injuries": 8,
    "last_accident_date": "2026-07-29",
    "dominant_cause": "High-Speed Transit & Wildlife Crossing in Flood Season",
    "dominant_type": "Collision with Wildlife & Overturning",
    "highest_risk_month": "July",
    "hotspot_score": 83.5,
    "hotspot_tier": "Critical",
    "primary_source": "Assam State PWD Highway Division",
    "dominant_vehicle": "Interstate Night Coach & Heavy Goods Carrier"
  },
  {
    "location_id": "loc-ml-byrnihat-nh6",
    "road_name": "Guwahati-Shillong Highway",
    "road_number": "NH-06",
    "city": "Byrnihat",
    "locality": "Assam-Meghalaya Border Descent Curve",
    "latitude": 26.0412,
    "longitude": 91.8712,
    "road_type": "National Highway",
    "state_id": "state-ml",
    "state_name": "Meghalaya",
    "state_code": "ML",
    "district_id": "dist-ri-bhoi",
    "district_name": "Ri-Bhoi",
    "total_accidents": 7,
    "fatal_accidents": 4,
    "total_deaths": 15,
    "total_injuries": 34,
    "total_critical_injuries": 9,
    "last_accident_date": "2026-08-03",
    "dominant_cause": "Heavy Rain Slickness & Coal Truck Brake Loss",
    "dominant_type": "Head-on / Hill Collision",
    "highest_risk_month": "June",
    "hotspot_score": 84,
    "hotspot_tier": "Critical",
    "primary_source": "Meghalaya Police Traffic Branch",
    "dominant_vehicle": "Heavy Coal Truck & Tourist Car"
  },
  {
    "location_id": "loc-jh-ranchi-tata-nh33",
    "road_name": "Ranchi-Jamshedpur Highway",
    "road_number": "NH-33",
    "city": "Chandil",
    "locality": "Rampur-Chowka Valley Hairpin Descent",
    "latitude": 22.9412,
    "longitude": 85.9812,
    "road_type": "National Highway",
    "state_id": "state-jh",
    "state_name": "Jharkhand",
    "state_code": "JH",
    "district_id": "dist-saraikela-kharsawan",
    "district_name": "Saraikela Kharsawan",
    "total_accidents": 9,
    "fatal_accidents": 5,
    "total_deaths": 21,
    "total_injuries": 46,
    "total_critical_injuries": 13,
    "last_accident_date": "2026-08-11",
    "dominant_cause": "Heavy Steel Trailer Brake Failure & Narrow Bridge",
    "dominant_type": "Head-on Collision / Barrier Impact",
    "highest_risk_month": "May",
    "hotspot_score": 91,
    "hotspot_tier": "Critical",
    "primary_source": "Jharkhand State Road Safety Council",
    "dominant_vehicle": "Steel Coil Multi-Axle Trailer"
  },
  {
    "location_id": "loc-br-ganga-setu-nh19",
    "road_name": "Mahatma Gandhi Setu Approach Highway",
    "road_number": "NH-19",
    "city": "Hajipur",
    "locality": "Ganga Setu North Bank Convergence",
    "latitude": 25.6812,
    "longitude": 85.2124,
    "road_type": "National Highway",
    "state_id": "state-br",
    "state_name": "Bihar",
    "state_code": "BR",
    "district_id": "dist-vaishali",
    "district_name": "Vaishali",
    "total_accidents": 9,
    "fatal_accidents": 5,
    "total_deaths": 18,
    "total_injuries": 48,
    "total_critical_injuries": 12,
    "last_accident_date": "2026-08-06",
    "dominant_cause": "Extreme Heavy Vehicle Congestion & Overtaking",
    "dominant_type": "Rear-end & Broadside",
    "highest_risk_month": "February",
    "hotspot_score": 88,
    "hotspot_tier": "Critical",
    "primary_source": "Bihar Transport Department Safety Cell",
    "dominant_vehicle": "Overloaded Sand Truck & Bus"
  }
];
